#!/usr/bin/env python3
"""Generate ~20,000 English-Chinese vocabulary entries for LibreLingo zh-en course."""

import json, uuid, os, itertools

CHALLENGES_DIR = "/Users/lys/LibreLingo/apps/librelingo-web/src/courses/zh-en/challenges"
os.makedirs(CHALLENGES_DIR, exist_ok=True)

def rand_id():
    return uuid.uuid4().hex[:12]

def make_entries(word, meaning):
    """Generate options + listeningExercise entries for a word pair."""
    g = rand_id()
    return [
        {"type": "options", "formInTargetLanguage": word, "meaningInSourceLanguage": meaning,
         "id": rand_id(), "priority": 0, "group": g},
        {"type": "listeningExercise", "answer": word, "meaning": meaning,
         "audio": uuid.uuid4().hex, "id": rand_id(), "priority": 1, "group": g}
    ]

def write_skill(skill_name, word_pairs, title, levels=5):
    """Write a skill JSON file with challenges."""
    challenges = []
    for w, m in word_pairs:
        challenges.extend(make_entries(w.strip(), m.strip()))
    skill_file = os.path.join(CHALLENGES_DIR, f"{skill_name}.json")
    with open(skill_file, "w", encoding="utf-8") as f:
        json.dump({"id": rand_id(), "levels": levels, "challenges": challenges}, f, ensure_ascii=False, indent=2)
    print(f"  {skill_name}: {len(word_pairs)} words ({len(challenges)} entries) -> {skill_file}")
    return {
        "imageSet": ["thumbnail1", "thumbnail2", "thumbnail3"],
        "summary": [w for w, _ in word_pairs[:30]],
        "practiceHref": skill_name,
        "id": rand_id(),
        "title": title,
        "levels": levels
    }

# ============ VOCABULARY DEFINITIONS ============

# 1. GREETINGS & BASICS (~500)
greetings = [
    ("Hello", "你好"), ("Goodbye", "再见"), ("Good morning", "早上好"), ("Good afternoon", "下午好"),
    ("Good evening", "晚上好"), ("Good night", "晚安"), ("How are you?", "你好吗？"),
    ("I'm fine, thank you", "我很好，谢谢"), ("Please", "请"), ("Thank you", "谢谢"),
    ("You're welcome", "不客气"), ("Sorry", "对不起"), ("Excuse me", "打扰一下"),
    ("Yes", "是的"), ("No", "不是"), ("Maybe", "也许"), ("Please help me", "请帮帮我"),
    ("I don't understand", "我不明白"), ("Could you repeat that?", "你能重复一遍吗？"),
    ("What is your name?", "你叫什么名字？"), ("My name is...", "我的名字是..."),
    ("Nice to meet you", "很高兴认识你"), ("Where are you from?", "你从哪里来？"),
    ("I am from China", "我来自中国"), ("How old are you?", "你多大了？"),
    ("I am... years old", "我...岁"), ("What do you do?", "你是做什么的？"),
    ("I am a student", "我是一个学生"), ("I am a teacher", "我是一个老师"),
    ("Welcome", "欢迎"), ("Have a nice day", "祝你愉快"), ("Take care", "保重"),
    ("See you later", "一会儿见"), ("See you tomorrow", "明天见"), ("Long time no see", "好久不见"),
    ("How's everything?", "一切都好吗？"), ("Pretty good", "还不错"),
    ("Same as usual", "和往常一样"), ("What's up?", "怎么了？"), ("Not much", "没什么"),
    ("I'm busy", "我很忙"), ("I'm tired", "我累了"), ("I'm hungry", "我饿了"),
    ("I'm thirsty", "我渴了"), ("I'm happy", "我很开心"), ("I'm sad", "我很难过"),
    ("Congratulations", "恭喜"), ("Happy birthday", "生日快乐"), ("Happy New Year", "新年快乐"),
    ("Merry Christmas", "圣诞节快乐"), ("Best wishes", "最美好的祝福"),
    ("Good luck", "祝你好运"), ("Well done", "做得好"), ("That's great", "太棒了"),
    ("No problem", "没问题"), ("It doesn't matter", "没关系"), ("Never mind", "不要紧"),
    ("Of course", "当然"), ("Absolutely", "当然"), ("Exactly", "正是"),
    ("Really?", "真的吗？"), ("Are you sure?", "你确定吗？"), ("I think so", "我想是的"),
    ("I don't know", "我不知道"), ("I agree", "我同意"), ("I disagree", "我不同意"),
    ("That's correct", "那是正确的"), ("That's wrong", "那是错的"),
    ("What?", "什么？"), ("When?", "什么时候？"), ("Where?", "在哪里？"),
    ("Why?", "为什么？"), ("How?", "怎么？"), ("Who?", "谁？"),
    ("Which?", "哪一个？"), ("Whose?", "谁的？"), ("How many?", "多少？"),
    ("How much?", "多少钱？"), ("How long?", "多长时间？"),
    ("How often?", "多久一次？"), ("How far?", "多远？"),
    ("Please speak slowly", "请说慢点"), ("I speak a little English", "我会说一点英语"),
    ("Do you speak Chinese?", "你会说中文吗？"),
    ("Can you write it down?", "你能写下来吗？"),
    ("What does this mean?", "这是什么意思？"),
    ("How do you say this?", "这个怎么说？"),
]

# 2. NUMBERS (1000 numbers) - 20 per line
numbers_words = []
number_chinese = {
    0: "零", 1:"一",2:"二",3:"三",4:"四",5:"五",6:"六",7:"七",8:"八",9:"九",10:"十",
    11:"十一",12:"十二",13:"十三",14:"十四",15:"十五",16:"十六",17:"十七",18:"十八",19:"十九",
    20:"二十",21:"二十一",22:"二十二",23:"二十三",24:"二十四",25:"二十五",26:"二十六",27:"二十七",
    28:"二十八",29:"二十九",30:"三十",31:"三十一",32:"三十二",33:"三十三",34:"三十四",35:"三十五",
    36:"三十六",37:"三十七",38:"三十八",39:"三十九",40:"四十",41:"四十一",42:"四十二",43:"四十三",
    44:"四十四",45:"四十五",46:"四十六",47:"四十七",48:"四十八",49:"四十九",50:"五十",
    51:"五十一",52:"五十二",53:"五十三",54:"五十四",55:"五十五",56:"五十六",57:"五十七",58:"五十八",
    59:"五十九",60:"六十",61:"六十一",62:"六十二",63:"六十三",64:"六十四",65:"六十五",66:"六十六",
    67:"六十七",68:"六十八",69:"六十九",70:"七十",71:"七十一",72:"七十二",73:"七十三",74:"七十四",
    75:"七十五",76:"七十六",77:"七十七",78:"七十八",79:"七十九",80:"八十",81:"八十一",82:"八十二",
    83:"八十三",84:"八十四",85:"八十五",86:"八十六",87:"八十七",88:"八十八",89:"八十九",90:"九十",
    91:"九十一",92:"九十二",93:"九十三",94:"九十四",95:"九十五",96:"九十六",97:"九十七",98:"九十八",
    99:"九十九",100:"一百",200:"两百",300:"三百",400:"四百",500:"五百",600:"六百",700:"七百",
    800:"八百",900:"九百",1000:"一千"
}
for n in range(1, 1001):
    ch = number_chinese.get(n)
    if ch:
        numbers_words.append((str(n), ch))
    else:
        # Handle 101-999
        h = n // 100
        r = n % 100
        hc = number_chinese[h] + "百"
        if r == 0:
            numbers_words.append((str(n), hc))
        else:
            rc = number_chinese[r] if r in number_chinese else (number_chinese[r//10*10] + number_chinese[r%10] if r > 10 else number_chinese[r])
            numbers_words.append((str(n), hc + rc))

# Combine numbers with ordinal words
numbers_extras = [
    ("first", "第一"), ("second", "第二"), ("third", "第三"), ("fourth", "第四"),
    ("fifth", "第五"), ("sixth", "第六"), ("seventh", "第七"), ("eighth", "第八"),
    ("ninth", "第九"), ("tenth", "第十"), ("half", "一半"), ("double", "双倍"),
    ("triple", "三倍"), ("hundred", "百"), ("thousand", "千"), ("ten thousand", "一万"),
    ("million", "百万"), ("billion", "十亿"), ("dozen", "一打"), ("pair", "一对"),
    ("zero", "零"), ("once", "一次"), ("twice", "两次"), ("three times", "三次"),
]

# 3. DAYS, MONTHS, TIME (~200)
times = [
    ("Monday", "星期一"), ("Tuesday", "星期二"), ("Wednesday", "星期三"),
    ("Thursday", "星期四"), ("Friday", "星期五"), ("Saturday", "星期六"), ("Sunday", "星期天"),
    ("weekday", "工作日"), ("weekend", "周末"), ("today", "今天"), ("yesterday", "昨天"),
    ("tomorrow", "明天"), ("day", "天"), ("night", "晚上"), ("morning", "早上"),
    ("afternoon", "下午"), ("evening", "傍晚"), ("noon", "中午"), ("midnight", "午夜"),
    ("dawn", "黎明"), ("dusk", "黄昏"), ("now", "现在"), ("later", "稍后"),
    ("soon", "很快"), ("early", "早"), ("late", "晚"), ("before", "之前"),
    ("after", "之后"), ("during", "期间"), ("while", "当...的时候"),
    ("January", "一月"), ("February", "二月"), ("March", "三月"),
    ("April", "四月"), ("May", "五月"), ("June", "六月"),
    ("July", "七月"), ("August", "八月"), ("September", "九月"),
    ("October", "十月"), ("November", "十一月"), ("December", "十二月"),
    ("spring", "春天"), ("summer", "夏天"), ("autumn", "秋天"), ("winter", "冬天"),
    ("season", "季节"), ("month", "月"), ("year", "年"), ("week", "周"),
    ("hour", "小时"), ("minute", "分钟"), ("second", "秒"), ("century", "世纪"),
    ("decade", "十年"), ("schedule", "日程"), ("appointment", "预约"),
    ("deadline", "截止日期"), ("delay", "延迟"), ("on time", "准时"),
    ("right now", "现在"), ("immediately", "立刻"), ("frequently", "经常"),
    ("rarely", "很少"), ("occasionally", "偶尔"), ("always", "总是"),
    ("usually", "通常"), ("sometimes", "有时"), ("never", "从不"),
    ("every day", "每天"), ("every week", "每周"), ("every month", "每月"),
    ("last week", "上周"), ("next week", "下周"), ("this week", "这周"),
    ("ago", "之前"), ("in the future", "将来"), ("currently", "目前"),
    ("meanwhile", "与此同时"), ("eventually", "最终"), ("finally", "最后"),
    ("immediately", "立即"), ("suddenly", "突然"), ("gradually", "逐渐"),
    ("hourly", "每小时"), ("daily", "每天"), ("weekly", "每周"), ("monthly", "每月"),
    ("annually", "每年"), ("clock", "时钟"), ("alarm", "闹钟"), ("calendar", "日历"),
    ("timetable", "时间表"), ("stopwatch", "秒表"), ("sundial", "日晷"),
]

# 4. COLORS (~50)
colors = [
    ("red", "红色"), ("blue", "蓝色"), ("green", "绿色"), ("yellow", "黄色"),
    ("white", "白色"), ("black", "黑色"), ("gray", "灰色"), ("brown", "棕色"),
    ("pink", "粉色"), ("purple", "紫色"), ("orange", "橙色"), ("gold", "金色"),
    ("silver", "银色"), ("navy", "深蓝色"), ("beige", "米色"), ("cream", "奶油色"),
    ("maroon", "栗色"), ("teal", "蓝绿色"), ("indigo", "靛蓝"), ("violet", "紫罗兰"),
    ("turquoise", "绿松石色"), ("lavender", "薰衣草色"), ("coral", "珊瑚色"),
    ("salmon", "鲑鱼色"), ("mint", "薄荷色"), ("olive", "橄榄色"),
    ("peach", "桃色"), ("ivory", "象牙色"), ("charcoal", "炭灰色"),
    ("burgundy", "酒红色"), ("blonde", "金色"), ("bronze", "青铜色"),
    ("crimson", "深红"), ("emerald", "祖母绿"), ("ruby", "红宝石色"),
    ("sapphire", "蓝宝石色"), ("jade", "翡翠色"), ("amber", "琥珀色"),
    ("scarlet", "猩红色"), ("mauve", "紫红色"), ("aqua", "浅绿色"),
    ("lime", "酸橙色"), ("tan", "棕褐色"), ("khaki", "卡其色"),
    ("plum", "李子色"), ("wine", "酒红色"), ("fluorescent", "荧光色"),
    ("transparent", "透明的"), ("bright", "明亮的"), ("dark", "深色的"),
    ("light", "浅色的"), ("colorful", "多彩的"), ("shiny", "闪亮的"),
    ("dull", "暗淡的"), ("matching", "相配的"), ("contrasting", "对比的"),
]

# 5. FAMILY & PEOPLE (~400)
family = [
    ("mother", "母亲"), ("father", "父亲"), ("parents", "父母"), ("sister", "姐妹"),
    ("brother", "兄弟"), ("daughter", "女儿"), ("son", "儿子"), ("wife", "妻子"),
    ("husband", "丈夫"), ("grandmother", "祖母"), ("grandfather", "祖父"),
    ("aunt", "阿姨"), ("uncle", "叔叔"), ("cousin", "表亲"), ("nephew", "侄子"),
    ("niece", "侄女"), ("grandson", "孙子"), ("granddaughter", "孙女"),
    ("baby", "婴儿"), ("child", "孩子"), ("teenager", "青少年"), ("adult", "成年人"),
    ("friend", "朋友"), ("boyfriend", "男朋友"), ("girlfriend", "女朋友"),
    ("neighbor", "邻居"), ("classmate", "同学"), ("colleague", "同事"),
    ("boss", "老板"), ("employee", "员工"), ("manager", "经理"),
    ("customer", "客户"), ("client", "客户"), ("guest", "客人"), ("host", "主人"),
    ("stranger", "陌生人"), ("partner", "伙伴"), ("assistant", "助理"),
    ("volunteer", "志愿者"), ("member", "成员"), ("leader", "领导"),
    ("follower", "追随者"), ("team", "团队"), ("group", "小组"),
    ("generation", "一代"), ("ancestor", "祖先"), ("descendant", "后代"),
    ("relative", "亲戚"), ("twin", "双胞胎"), ("orphan", "孤儿"),
    ("widow", "寡妇"), ("widower", "鳏夫"), ("fiancé", "未婚夫"), ("fiancée", "未婚妻"),
    ("stepmother", "继母"), ("stepfather", "继父"), ("half-brother", "同父异母兄弟"),
    ("half-sister", "同父异母姐妹"), ("in-laws", "姻亲"),
    ("godfather", "教父"), ("godmother", "教母"), ("godchild", "教子"),
    ("bride", "新娘"), ("groom", "新郎"), ("best man", "伴郎"),
    ("bridesmaid", "伴娘"), ("single", "单身的"), ("married", "已婚的"),
    ("divorced", "离婚的"), ("engaged", "已订婚的"), ("separated", "分居的"),
    ("widowed", "丧偶的"),
]

# 6. BODY PARTS (~100)
body = [
    ("head", "头"), ("hair", "头发"), ("face", "脸"), ("eye", "眼睛"),
    ("nose", "鼻子"), ("mouth", "嘴"), ("ear", "耳朵"), ("neck", "脖子"),
    ("shoulder", "肩膀"), ("arm", "手臂"), ("hand", "手"), ("finger", "手指"),
    ("chest", "胸部"), ("back", "背部"), ("stomach", "肚子"), ("leg", "腿"),
    ("knee", "膝盖"), ("foot", "脚"), ("toe", "脚趾"), ("skin", "皮肤"),
    ("bone", "骨头"), ("muscle", "肌肉"), ("heart", "心脏"), ("lung", "肺"),
    ("liver", "肝脏"), ("kidney", "肾脏"), ("brain", "大脑"), ("blood", "血液"),
    ("eyebrow", "眉毛"), ("eyelash", "睫毛"), ("tongue", "舌头"), ("tooth", "牙齿"),
    ("lip", "嘴唇"), ("chin", "下巴"), ("cheek", "脸颊"), ("forehead", "额头"),
    ("jaw", "下巴"), ("wrist", "手腕"), ("ankle", "脚踝"), ("elbow", "肘部"),
    ("hip", "臀部"), ("waist", "腰"), ("thumb", "大拇指"), ("palm", "手掌"),
    ("fist", "拳头"), ("nail", "指甲"), ("heel", "脚后跟"), ("sole", "脚底"),
    ("spine", "脊柱"), ("rib", "肋骨"), ("throat", "喉咙"), ("vein", "静脉"),
    ("artery", "动脉"), ("nerve", "神经"), ("gland", "腺体"), ("organ", "器官"),
    ("pupil", "瞳孔"), ("iris", "虹膜"), ("eyelid", "眼睑"),
    ("nostril", "鼻孔"), ("palate", "上颚"), ("gum", "牙龈"),
    ("molar", "磨牙"), ("incisor", "门牙"), ("canine", "犬牙"),
    ("temple", "太阳穴"), ("skull", "头骨"), ("collarbone", "锁骨"),
    ("shoulder blade", "肩胛骨"), ("thigh", "大腿"), ("calf", "小腿"),
    ("shin", "胫骨"), ("instep", "脚背"), ("cuticle", "表皮"),
    ("knuckle", "指关节"), ("dimple", "酒窝"), ("freckle", "雀斑"),
    ("wrinkle", "皱纹"), ("mole", "痣"), ("birthmark", "胎记"),
]

# 7. CLOTHING & ACCESSORIES (~200)
clothing = [
    ("shirt", "衬衫"), ("pants", "裤子"), ("dress", "连衣裙"), ("skirt", "裙子"),
    ("jacket", "夹克"), ("coat", "外套"), ("sweater", "毛衣"), ("shorts", "短裤"),
    ("jeans", "牛仔裤"), ("suit", "西装"), ("tie", "领带"), ("belt", "腰带"),
    ("shoes", "鞋子"), ("socks", "袜子"), ("hat", "帽子"), ("gloves", "手套"),
    ("scarf", "围巾"), ("underwear", "内衣"), ("sneakers", "运动鞋"),
    ("boots", "靴子"), ("sandals", "凉鞋"), ("slippers", "拖鞋"),
    ("uniform", "制服"), ("pajamas", "睡衣"), ("swimsuit", "泳衣"),
    ("vest", "背心"), ("blazer", "西装外套"), ("blouse", "女衬衫"),
    ("cardigan", "开衫"), ("raincoat", "雨衣"), ("trench coat", "风衣"),
    ("tuxedo", "晚礼服"), ("gown", "长袍"), ("robe", "浴袍"),
    ("waistcoat", "马甲"), ("cufflinks", "袖扣"), ("zipper", "拉链"),
    ("button", "纽扣"), ("pocket", "口袋"), ("collar", "领子"),
    ("sleeve", "袖子"), ("hem", "下摆"), ("lining", "衬里"),
    ("fabric", "面料"), ("cotton", "棉"), ("silk", "丝绸"), ("wool", "羊毛"),
    ("leather", "皮革"), ("linen", "亚麻"), ("polyester", "聚酯纤维"),
    ("velvet", "天鹅绒"), ("lace", "蕾丝"), ("denim", "牛仔布"),
    ("necklace", "项链"), ("bracelet", "手链"), ("ring", "戒指"),
    ("earrings", "耳环"), ("watch", "手表"), ("glasses", "眼镜"),
    ("sunglasses", "太阳镜"), ("wallet", "钱包"), ("purse", "手提包"),
    ("backpack", "背包"), ("handbag", "手袋"), ("luggage", "行李"),
    ("umbrella", "雨伞"), ("towel", "毛巾"), ("handkerchief", "手帕"),
    ("mask", "口罩"), ("helmet", "头盔"), ("apron", "围裙"),
    ("shawl", "披肩"), ("muffler", "围巾"), ("bow tie", "蝴蝶结领结"),
    ("suspenders", "吊带裤"), ("stockings", "长袜"), ("tights", "紧身裤袜"),
    ("cap", "鸭舌帽"), ("beret", "贝雷帽"), ("beanie", "无檐帽"),
    ("visor", "遮阳帽"), ("headband", "发带"), ("hairpin", "发夹"),
    ("brooch", "胸针"), ("pendant", "吊坠"), ("anklet", "脚链"),
    ("cuff", "袖口"), ("placket", "门襟"), ("seam", "接缝"),
    ("dart", "省道"), ("pleat", "褶裥"), ("gusset", "插角"),
]

# 8. FOOD & DRINKS (~500)
food = [
    ("water", "水"), ("bread", "面包"), ("rice", "米饭"), ("noodles", "面条"),
    ("meat", "肉"), ("chicken", "鸡肉"), ("beef", "牛肉"), ("pork", "猪肉"),
    ("fish", "鱼"), ("egg", "鸡蛋"), ("milk", "牛奶"), ("cheese", "奶酪"),
    ("butter", "黄油"), ("yogurt", "酸奶"), ("cream", "奶油"),
    ("sugar", "糖"), ("salt", "盐"), ("pepper", "胡椒粉"), ("oil", "油"),
    ("vinegar", "醋"), ("soy sauce", "酱油"), ("honey", "蜂蜜"),
    ("jam", "果酱"), ("butter", "黄油"), ("ketchup", "番茄酱"),
    ("mustard", "芥末"), ("mayonnaise", "蛋黄酱"), ("spice", "香料"),
    ("garlic", "大蒜"), ("ginger", "姜"), ("onion", "洋葱"),
    ("tomato", "番茄"), ("potato", "土豆"), ("carrot", "胡萝卜"),
    ("cabbage", "卷心菜"), ("lettuce", "生菜"), ("cucumber", "黄瓜"),
    ("pepper", "辣椒"), ("mushroom", "蘑菇"), ("corn", "玉米"),
    ("bean", "豆子"), ("tofu", "豆腐"), ("apple", "苹果"), ("banana", "香蕉"),
    ("orange", "橙子"), ("grape", "葡萄"), ("watermelon", "西瓜"),
    ("strawberry", "草莓"), ("lemon", "柠檬"), ("lime", "青柠"),
    ("peach", "桃子"), ("pear", "梨"), ("cherry", "樱桃"),
    ("pineapple", "菠萝"), ("mango", "芒果"), ("kiwi", "猕猴桃"),
    ("coconut", "椰子"), ("avocado", "牛油果"), ("papaya", "木瓜"),
    ("cake", "蛋糕"), ("cookie", "饼干"), ("pie", "派"), ("bread", "面包"),
    ("sandwich", "三明治"), ("pizza", "比萨"), ("burger", "汉堡"),
    ("fries", "薯条"), ("soup", "汤"), ("salad", "沙拉"), ("steak", "牛排"),
    ("sushi", "寿司"), ("rice", "米饭"), ("porridge", "粥"), ("pancake", "煎饼"),
    ("toast", "烤面包"), ("cereal", "麦片"), ("omelette", "煎蛋卷"),
    ("bacon", "培根"), ("sausage", "香肠"), ("ham", "火腿"),
    ("tea", "茶"), ("coffee", "咖啡"), ("juice", "果汁"), ("soda", "汽水"),
    ("beer", "啤酒"), ("wine", "葡萄酒"), ("champagne", "香槟"),
    ("cocktail", "鸡尾酒"), ("whiskey", "威士忌"), ("vodka", "伏特加"),
    ("hot chocolate", "热巧克力"), ("milkshake", "奶昔"),
    ("lemonade", "柠檬水"), ("mineral water", "矿泉水"),
    ("appetizer", "开胃菜"), ("main course", "主菜"), ("dessert", "甜点"),
    ("breakfast", "早餐"), ("lunch", "午餐"), ("dinner", "晚餐"),
    ("snack", "小吃"), ("leftovers", "剩菜"), ("takeout", "外卖"),
    ("recipe", "食谱"), ("ingredient", "原料"), ("kitchen", "厨房"),
    ("stove", "炉子"), ("oven", "烤箱"), ("microwave", "微波炉"),
    ("refrigerator", "冰箱"), ("freezer", "冷冻室"), ("dishwasher", "洗碗机"),
    ("plate", "盘子"), ("bowl", "碗"), ("cup", "杯子"), ("glass", "玻璃杯"),
    ("fork", "叉子"), ("knife", "刀"), ("spoon", "勺子"), ("chopsticks", "筷子"),
    ("napkin", "餐巾"), ("tablecloth", "桌布"), ("tray", "托盘"),
    ("pot", "锅"), ("pan", "平底锅"), ("kettle", "水壶"), ("cutting board", "砧板"),
    ("strainer", "滤网"), ("rolling pin", "擀面杖"),
    ("baking", "烘焙"), ("frying", "油炸"), ("boiling", "煮"),
    ("steaming", "蒸"), ("grilling", "烧烤"), ("roasting", "烤"),
    ("stir-frying", "炒"), ("braising", "炖"), ("marinating", "腌制"),
    ("delicious", "美味的"), ("sour", "酸的"), ("sweet", "甜的"),
    ("bitter", "苦的"), ("spicy", "辣的"), ("salty", "咸的"),
    ("fresh", "新鲜的"), ("stale", "不新鲜的"), ("raw", "生的"),
    ("cooked", "熟的"), ("frozen", "冷冻的"), ("organic", "有机的"),
    ("vegetarian", "素食的"), ("vegan", "纯素的"), ("gluten-free", "无麸质的"),
    ("nutritious", "有营养的"), ("calorie", "卡路里"), ("diet", "饮食"),
    ("hungry", "饿的"), ("thirsty", "渴的"), ("full", "饱的"),
    ("taste", "味道"), ("flavor", "风味"), ("aroma", "香气"),
]

# 9. WEATHER & NATURE (~300)
weather_nature = [
    ("sunny", "晴朗的"), ("rainy", "下雨的"), ("cloudy", "多云的"),
    ("windy", "有风的"), ("snowy", "下雪的"), ("foggy", "有雾的"),
    ("stormy", "暴风雨的"), ("hot", "热的"), ("cold", "冷的"),
    ("warm", "温暖的"), ("cool", "凉爽的"), ("humid", "潮湿的"),
    ("dry", "干燥的"), ("temperature", "温度"), ("forecast", "天气预报"),
    ("rainbow", "彩虹"), ("thunder", "雷声"), ("lightning", "闪电"),
    ("flood", "洪水"), ("drought", "干旱"), ("hurricane", "飓风"),
    ("tornado", "龙卷风"), ("earthquake", "地震"), ("tsunami", "海啸"),
    ("volcano", "火山"), ("typhoon", "台风"), ("monsoon", "季风"),
    ("climate", "气候"), ("weather", "天气"), ("season", "季节"),
    ("tree", "树"), ("flower", "花"), ("grass", "草"), ("leaf", "叶子"),
    ("mountain", "山"), ("river", "河流"), ("lake", "湖"), ("ocean", "海洋"),
    ("sea", "海"), ("forest", "森林"), ("desert", "沙漠"), ("island", "岛屿"),
    ("valley", "山谷"), ("hill", "小山"), ("waterfall", "瀑布"),
    ("cave", "洞穴"), ("beach", "海滩"), ("coast", "海岸"),
    ("field", "田野"), ("garden", "花园"), ("park", "公园"),
    ("sky", "天空"), ("cloud", "云"), ("rain", "雨"), ("snow", "雪"),
    ("ice", "冰"), ("wind", "风"), ("air", "空气"), ("sun", "太阳"),
    ("moon", "月亮"), ("star", "星星"), ("planet", "行星"),
    ("earth", "地球"), ("fire", "火"), ("water", "水"), ("stone", "石头"),
    ("sand", "沙子"), ("soil", "土壤"), ("mud", "泥"),
    ("animal", "动物"), ("bird", "鸟"), ("cat", "猫"), ("dog", "狗"),
    ("horse", "马"), ("cow", "牛"), ("sheep", "羊"), ("pig", "猪"),
    ("rabbit", "兔子"), ("duck", "鸭子"), ("goose", "鹅"),
    ("elephant", "大象"), ("lion", "狮子"), ("tiger", "老虎"),
    ("bear", "熊"), ("wolf", "狼"), ("deer", "鹿"), ("fox", "狐狸"),
    ("monkey", "猴子"), ("panda", "熊猫"), ("kangaroo", "袋鼠"),
    ("whale", "鲸鱼"), ("dolphin", "海豚"), ("shark", "鲨鱼"),
    ("eagle", "鹰"), ("owl", "猫头鹰"), ("parrot", "鹦鹉"),
    ("snake", "蛇"), ("lizard", "蜥蜴"), ("turtle", "乌龟"),
    ("frog", "青蛙"), ("butterfly", "蝴蝶"), ("bee", "蜜蜂"),
    ("ant", "蚂蚁"), ("spider", "蜘蛛"), ("mosquito", "蚊子"),
    ("environment", "环境"), ("pollution", "污染"), ("recycle", "回收"),
    ("conservation", "保护"), ("ecosystem", "生态系统"), ("species", "物种"),
    ("extinction", "灭绝"), ("wildlife", "野生动物"), ("habitat", "栖息地"),
    ("energy", "能量"), ("solar", "太阳能的"), ("wind power", "风能"),
    ("renewable", "可再生的"), ("sustainable", "可持续的"),
    ("global warming", "全球变暖"), ("greenhouse", "温室"),
    ("carbon dioxide", "二氧化碳"), ("oxygen", "氧气"), ("nitrogen", "氮气"),
]

# 10. DAILY LIFE & HOME (~500)
daily_life = [
    ("house", "房子"), ("apartment", "公寓"), ("room", "房间"),
    ("bedroom", "卧室"), ("living room", "客厅"), ("kitchen", "厨房"),
    ("bathroom", "浴室"), ("dining room", "餐厅"), ("study", "书房"),
    ("balcony", "阳台"), ("garage", "车库"), ("garden", "花园"),
    ("door", "门"), ("window", "窗户"), ("wall", "墙"), ("floor", "地板"),
    ("ceiling", "天花板"), ("roof", "屋顶"), ("stairs", "楼梯"),
    ("furniture", "家具"), ("table", "桌子"), ("chair", "椅子"),
    ("sofa", "沙发"), ("bed", "床"), ("desk", "书桌"), ("bookshelf", "书架"),
    ("cabinet", "柜子"), ("drawer", "抽屉"), ("mirror", "镜子"),
    ("lamp", "灯"), ("curtain", "窗帘"), ("carpet", "地毯"),
    ("pillow", "枕头"), ("blanket", "毯子"), ("sheet", "床单"),
    ("towel", "毛巾"), ("soap", "肥皂"), ("shampoo", "洗发水"),
    ("toothbrush", "牙刷"), ("toothpaste", "牙膏"), ("comb", "梳子"),
    ("toilet", "马桶"), ("shower", "淋浴"), ("bathtub", "浴缸"),
    ("sink", "水槽"), ("tap", "水龙头"), ("bucket", "水桶"),
    ("broom", "扫帚"), ("mop", "拖把"), ("detergent", "清洁剂"),
    ("trash", "垃圾"), ("recycle bin", "回收箱"), ("key", "钥匙"),
    ("lock", "锁"), ("remote control", "遥控器"), ("switch", "开关"),
    ("plug", "插头"), ("socket", "插座"), ("battery", "电池"),
    ("alarm clock", "闹钟"), ("telephone", "电话"), ("television", "电视"),
    ("computer", "电脑"), ("laptop", "笔记本电脑"), ("tablet", "平板电脑"),
    ("phone", "手机"), ("charger", "充电器"), ("headphones", "耳机"),
    ("speaker", "扬声器"), ("camera", "相机"), ("printer", "打印机"),
    ("washing machine", "洗衣机"), ("dryer", "烘干机"),
    ("vacuum cleaner", "吸尘器"), ("iron", "熨斗"), ("sewing machine", "缝纫机"),
    ("cooking", "烹饪"), ("cleaning", "打扫"), ("laundry", "洗衣"),
    ("gardening", "园艺"), ("repair", "修理"), ("decorating", "装饰"),
    ("rent", "租金"), ("mortgage", "房贷"), ("utility", "水电费"),
    ("electricity", "电"), ("gas", "煤气"), ("water bill", "水费"),
    ("neighbor", "邻居"), ("landlord", "房东"), ("tenant", "租客"),
    ("mail", "邮件"), ("package", "包裹"), ("delivery", "递送"),
    ("garbage", "垃圾"), ("recycling", "回收"), ("parking", "停车"),
    ("elevator", "电梯"), ("lobby", "大堂"), ("hallway", "走廊"),
    ("attic", "阁楼"), ("basement", "地下室"), ("yard", "院子"),
    ("fence", "围栏"), ("gate", "大门"), ("porch", "门廊"),
    ("wake up", "起床"), ("get dressed", "穿衣服"), ("eat breakfast", "吃早餐"),
    ("go to work", "去上班"), ("come home", "回家"), ("have dinner", "吃晚餐"),
    ("take a shower", "洗澡"), ("brush teeth", "刷牙"), ("go to bed", "上床睡觉"),
    ("sleep", "睡觉"), ("dream", "做梦"), ("alarm", "闹钟"),
    ("breakfast", "早餐"), ("lunch", "午餐"), ("dinner", "晚餐"),
    ("snack", "零食"), ("meal", "一餐"), ("cook", "做饭"),
    ("wash dishes", "洗碗"), ("do laundry", "洗衣服"), ("clean", "打扫"),
    ("tidy up", "整理"), ("make the bed", "铺床"), ("dust", "除尘"),
    ("vacuum", "吸尘"), ("sweep", "扫地"), ("mop", "拖地"),
    ("water plants", "浇花"), ("feed pets", "喂宠物"), ("take out trash", "倒垃圾"),
    ("lock the door", "锁门"), ("turn off lights", "关灯"),
    ("set alarm", "设闹钟"), ("check email", "查邮件"), ("read news", "看新闻"),
    ("exercise", "锻炼"), ("meditate", "冥想"), ("shopping", "购物"),
    ("errand", "跑腿"), ("commute", "通勤"), ("traffic", "交通"),
]

# 11. HEALTH & MEDICINE (~500)
health = [
    ("doctor", "医生"), ("nurse", "护士"), ("hospital", "医院"),
    ("clinic", "诊所"), ("pharmacy", "药房"), ("medicine", "药"),
    ("pill", "药片"), ("tablet", "药片"), ("capsule", "胶囊"),
    ("syrup", "糖浆"), ("injection", "注射"), ("vaccine", "疫苗"),
    ("prescription", "处方"), ("symptom", "症状"), ("fever", "发烧"),
    ("cough", "咳嗽"), ("cold", "感冒"), ("flu", "流感"),
    ("headache", "头痛"), ("stomachache", "胃痛"), ("toothache", "牙痛"),
    ("sore throat", "喉咙痛"), ("runny nose", "流鼻涕"),
    ("allergy", "过敏"), ("infection", "感染"), ("inflammation", "炎症"),
    ("wound", "伤口"), ("bruise", "瘀伤"), ("fracture", "骨折"),
    ("sprain", "扭伤"), ("pain", "疼痛"), ("ache", "疼痛"),
    ("dizzy", "头晕的"), ("nausea", "恶心"), ("vomit", "呕吐"),
    ("diarrhea", "腹泻"), ("constipation", "便秘"), ("insomnia", "失眠"),
    ("blood pressure", "血压"), ("diabetes", "糖尿病"), ("asthma", "哮喘"),
    ("cancer", "癌症"), ("heart disease", "心脏病"), ("stroke", "中风"),
    ("surgery", "手术"), ("therapy", "治疗"), ("diagnosis", "诊断"),
    ("examination", "检查"), ("test", "检测"), ("X-ray", "X光"),
    ("CT scan", "CT扫描"), ("MRI", "核磁共振"), ("ultrasound", "超声波"),
    ("check-up", "体检"), ("emergency", "急诊"), ("ambulance", "救护车"),
    ("first aid", "急救"), ("bandage", "绷带"), ("plaster", "创可贴"),
    ("thermometer", "温度计"), ("stethoscope", "听诊器"),
    ("wheelchair", "轮椅"), ("crutches", "拐杖"), ("glasses", "眼镜"),
    ("contact lens", "隐形眼镜"), ("hearing aid", "助听器"),
    ("exercise", "锻炼"), ("yoga", "瑜伽"), ("swimming", "游泳"),
    ("running", "跑步"), ("walking", "步行"), ("gym", "健身房"),
    ("diet", "饮食"), ("nutrition", "营养"), ("protein", "蛋白质"),
    ("vitamin", "维生素"), ("mineral", "矿物质"), ("fiber", "纤维"),
    ("calcium", "钙"), ("iron", "铁"), ("zinc", "锌"),
    ("healthy", "健康的"), ("unhealthy", "不健康的"),
    ("mental health", "心理健康"), ("stress", "压力"), ("anxiety", "焦虑"),
    ("depression", "抑郁"), ("relaxation", "放松"), ("massage", "按摩"),
    ("acupuncture", "针灸"), ("herbal medicine", "中药"),
    ("sleep", "睡眠"), ("rest", "休息"), ("recovery", "恢复"),
    ("immunity", "免疫力"), ("virus", "病毒"), ("bacteria", "细菌"),
    ("chronic", "慢性的"), ("acute", "急性的"), ("benign", "良性的"),
    ("malignant", "恶性的"), ("side effect", "副作用"),
    ("dosage", "剂量"), ("overdose", "过量"),
    ("allergist", "过敏科医生"), ("cardiologist", "心脏科医生"),
    ("dentist", "牙医"), ("dermatologist", "皮肤科医生"),
    ("gynecologist", "妇科医生"), ("pediatrician", "儿科医生"),
    ("psychiatrist", "精神科医生"), ("surgeon", "外科医生"),
    ("orthopedist", "骨科医生"), ("ophthalmologist", "眼科医生"),
    ("health insurance", "健康保险"), ("medical record", "病历"),
    ("operation", "手术"), ("transplant", "移植"),
    ("pregnancy", "怀孕"), ("childbirth", "分娩"), ("breastfeeding", "母乳喂养"),
    ("vaccination", "接种疫苗"), ("quarantine", "隔离"),
    ("sanitizer", "消毒液"), ("mask", "口罩"), ("gloves", "手套"),
]

# 12. EDUCATION & LEARNING (~800)
education = [
    ("school", "学校"), ("university", "大学"), ("college", "学院"),
    ("kindergarten", "幼儿园"), ("class", "班级"), ("classroom", "教室"),
    ("teacher", "老师"), ("student", "学生"), ("professor", "教授"),
    ("lecturer", "讲师"), ("principal", "校长"), ("dean", "院长"),
    ("tutor", "家教"), ("scholar", "学者"), ("graduate", "毕业生"),
    ("undergraduate", "本科生"), ("postgraduate", "研究生"),
    ("doctorate", "博士学位"), ("master", "硕士"), ("bachelor", "学士"),
    ("diploma", "文凭"), ("certificate", "证书"),
    ("subject", "科目"), ("mathematics", "数学"), ("physics", "物理"),
    ("chemistry", "化学"), ("biology", "生物"), ("history", "历史"),
    ("geography", "地理"), ("literature", "文学"), ("philosophy", "哲学"),
    ("psychology", "心理学"), ("sociology", "社会学"), ("economics", "经济学"),
    ("political science", "政治学"), ("engineering", "工程学"),
    ("computer science", "计算机科学"), ("medicine", "医学"),
    ("law", "法律"), ("architecture", "建筑学"), ("business", "商学"),
    ("accounting", "会计学"), ("marketing", "市场营销"),
    ("linguistics", "语言学"), ("anthropology", "人类学"),
    ("exam", "考试"), ("test", "测验"), ("quiz", "小测验"),
    ("homework", "作业"), ("assignment", "作业"), ("project", "项目"),
    ("research", "研究"), ("paper", "论文"), ("thesis", "论文"),
    ("dissertation", "博士论文"), ("essay", "文章"), ("report", "报告"),
    ("presentation", "演示"), ("seminar", "研讨会"), ("lecture", "讲座"),
    ("workshop", "工作坊"), ("tutorial", "辅导课"), ("lesson", "课"),
    ("course", "课程"), ("syllabus", "教学大纲"), ("curriculum", "课程"),
    ("grade", "成绩"), ("score", "分数"), ("mark", "分数"),
    ("pass", "通过"), ("fail", "不及格"), ("retake", "补考"),
    ("scholarship", "奖学金"), ("tuition", "学费"), ("grant", "助学金"),
    ("library", "图书馆"), ("book", "书"), ("textbook", "教科书"),
    ("dictionary", "词典"), ("encyclopedia", "百科全书"),
    ("notebook", "笔记本"), ("pen", "笔"), ("pencil", "铅笔"),
    ("eraser", "橡皮"), ("ruler", "尺子"), ("calculator", "计算器"),
    ("computer", "电脑"), ("projector", "投影仪"), ("whiteboard", "白板"),
    ("blackboard", "黑板"), ("chalk", "粉笔"),
    ("read", "阅读"), ("write", "写"), ("listen", "听"), ("speak", "说"),
    ("learn", "学习"), ("study", "学习"), ("teach", "教"), ("explain", "解释"),
    ("understand", "理解"), ("memorize", "记忆"), ("review", "复习"),
    ("practice", "练习"), ("research", "研究"), ("analyze", "分析"),
    ("discuss", "讨论"), ("debate", "辩论"), ("present", "展示"),
    ("homework", "家庭作业"), ("assignment", "作业"),
    ("deadline", "截止日期"), ("extension", "延期"), ("plagiarism", "抄袭"),
    ("citation", "引用"), ("reference", "参考"), ("bibliography", "参考文献"),
    ("footnote", "脚注"), ("appendix", "附录"), ("index", "索引"),
    ("chapter", "章节"), ("paragraph", "段落"), ("sentence", "句子"),
    ("vocabulary", "词汇"), ("grammar", "语法"), ("pronunciation", "发音"),
    ("reading", "阅读"), ("writing", "写作"), ("listening", "听力"),
    ("speaking", "口语"), ("translation", "翻译"),
    ("fluent", "流利的"), ("proficient", "熟练的"),
    ("beginner", "初学者"), ("intermediate", "中级的"),
    ("advanced", "高级的"), ("native", "母语的"),
    ("kindergarten", "幼儿园"), ("primary school", "小学"),
    ("middle school", "中学"), ("high school", "高中"),
    ("vocational school", "职业学校"), ("graduate school", "研究生院"),
    ("academic", "学术的"), ("extracurricular", "课外的"),
    ("campus", "校园"), ("dormitory", "宿舍"), ("cafeteria", "食堂"),
    ("laboratory", "实验室"), ("auditorium", "礼堂"),
    ("language", "语言"), ("Chinese", "中文"), ("English", "英语"),
    ("French", "法语"), ("Spanish", "西班牙语"), ("German", "德语"),
    ("Japanese", "日语"), ("Korean", "韩语"), ("Russian", "俄语"),
    ("Arabic", "阿拉伯语"), ("Italian", "意大利语"), ("Portuguese", "葡萄牙语"),
    ("knowledge", "知识"), ("wisdom", "智慧"), ("intelligence", "智力"),
    ("thinking", "思考"), ("creativity", "创造力"), ("innovation", "创新"),
    ("problem-solving", "解决问题"), ("critical thinking", "批判性思维"),
    ("study abroad", "出国留学"), ("exchange program", "交换项目"),
    ("degree", "学位"), ("major", "专业"), ("minor", "辅修"),
    ("credit", "学分"), ("transcript", "成绩单"),
    ("graduation", "毕业"), ("commencement", "毕业典礼"),
    ("alumni", "校友"), ("faculty", "教职员工"), ("staff", "员工"),
    ("enroll", "注册"), ("register", "登记"), ("apply", "申请"),
    ("admission", "录取"), ("acceptance", "录取通知"),
    ("orientation", "迎新会"), ("freshman", "大一新生"),
    ("sophomore", "大二学生"), ("junior", "大三学生"), ("senior", "大四学生"),
    ("bilingual", "双语的"), ("multilingual", "多语的"),
    ("literacy", "读写能力"), ("numeracy", "计算能力"),
]

# 13. WORK & BUSINESS (~1000)
work_business = [
    ("job", "工作"), ("career", "职业"), ("profession", "专业"), ("occupation", "职业"),
    ("company", "公司"), ("office", "办公室"), ("factory", "工厂"),
    ("headquarters", "总部"), ("branch", "分公司"),
    ("manager", "经理"), ("director", "总监"), ("CEO", "首席执行官"),
    ("CFO", "首席财务官"), ("CTO", "首席技术官"),
    ("employee", "员工"), ("employer", "雇主"), ("intern", "实习生"),
    ("colleague", "同事"), ("supervisor", "主管"), ("subordinate", "下属"),
    ("entrepreneur", "企业家"), ("consultant", "顾问"),
    ("freelancer", "自由职业者"), ("contractor", "承包商"),
    ("accountant", "会计"), ("lawyer", "律师"), ("engineer", "工程师"),
    ("programmer", "程序员"), ("designer", "设计师"),
    ("analyst", "分析师"), ("marketer", "市场营销人员"),
    ("salesperson", "销售人员"), ("receptionist", "前台"),
    ("secretary", "秘书"), ("assistant", "助理"),
    ("meeting", "会议"), ("appointment", "约见"), ("schedule", "日程"),
    ("agenda", "议程"), ("minutes", "会议记录"), ("deadline", "截止日期"),
    ("project", "项目"), ("task", "任务"), ("assignment", "任务分配"),
    ("report", "报告"), ("proposal", "提案"), ("budget", "预算"),
    ("contract", "合同"), ("invoice", "发票"), ("receipt", "收据"),
    ("salary", "工资"), ("wage", "时薪"), ("bonus", "奖金"),
    ("commission", "佣金"), ("benefit", "福利"), ("insurance", "保险"),
    ("pension", "养老金"), ("tax", "税"), ("deduction", "扣除"),
    ("promotion", "升职"), ("transfer", "调职"), ("resignation", "辞职"),
    ("layoff", "裁员"), ("retirement", "退休"),
    ("interview", "面试"), ("resume", "简历"), ("cover letter", "求职信"),
    ("recruitment", "招聘"), ("hire", "雇佣"), ("fire", "解雇"),
    ("training", "培训"), ("orientation", "入职培训"),
    ("performance", "绩效"), ("evaluation", "评估"),
    ("networking", "社交"), ("negotiation", "谈判"),
    ("presentation", "演示"), ("speech", "演讲"),
    ("teamwork", "团队合作"), ("leadership", "领导力"),
    ("communication", "沟通"), ("cooperation", "合作"),
    ("strategy", "战略"), ("plan", "计划"), ("goal", "目标"),
    ("mission", "使命"), ("vision", "愿景"), ("value", "价值观"),
    ("customer", "客户"), ("client", "客户"), ("supplier", "供应商"),
    ("partner", "合作伙伴"), ("stakeholder", "利益相关者"),
    ("market", "市场"), ("sales", "销售"), ("marketing", "营销"),
    ("advertising", "广告"), ("brand", "品牌"), ("logo", "标志"),
    ("product", "产品"), ("service", "服务"), ("quality", "质量"),
    ("price", "价格"), ("cost", "成本"), ("profit", "利润"),
    ("revenue", "收入"), ("expense", "支出"), ("loss", "亏损"),
    ("investment", "投资"), ("funding", "融资"), ("loan", "贷款"),
    ("credit", "信用"), ("debt", "债务"), ("asset", "资产"),
    ("liability", "负债"), ("equity", "股权"), ("share", "股份"),
    ("stock", "股票"), ("bond", "债券"), ("dividend", "股息"),
    ("interest", "利息"), ("inflation", "通胀"), ("recession", "衰退"),
    ("economy", "经济"), ("GDP", "国内生产总值"), ("trade", "贸易"),
    ("import", "进口"), ("export", "出口"), ("tariff", "关税"),
    ("globalization", "全球化"), ("outsourcing", "外包"),
    ("innovation", "创新"), ("R&D", "研发"),
    ("workplace", "工作场所"), ("culture", "文化"), ("policy", "政策"),
    ("regulation", "规定"), ("compliance", "合规"),
    ("remote work", "远程工作"), ("flexible hours", "弹性工作时间"),
    ("overtime", "加班"), ("shift", "轮班"), ("workload", "工作量"),
    ("productivity", "生产力"), ("efficiency", "效率"),
    ("business trip", "出差"), ("conference", "会议"),
    ("negotiate", "谈判"), ("pitch", "推销"), ("deal", "交易"),
    ("partnership", "合作关系"), ("merger", "合并"), ("acquisition", "收购"),
    ("IPO", "首次公开募股"), ("startup", "初创公司"),
    ("venture capital", "风险投资"), ("angel investor", "天使投资人"),
    ("business plan", "商业计划"), ("feasibility", "可行性"),
    ("supply chain", "供应链"), ("logistics", "物流"),
    ("warehouse", "仓库"), ("inventory", "库存"),
    ("procurement", "采购"), ("purchase order", "采购订单"),
    ("invoice", "发票"), ("payment terms", "付款条件"),
    ("audit", "审计"), ("compliance", "合规"), ("ethics", "道德"),
    ("corporate social responsibility", "企业社会责任"),
]

# 14. TECHNOLOGY & COMPUTER (~500)
technology = [
    ("computer", "电脑"), ("laptop", "笔记本电脑"), ("desktop", "台式机"),
    ("tablet", "平板电脑"), ("smartphone", "智能手机"),
    ("monitor", "显示器"), ("keyboard", "键盘"), ("mouse", "鼠标"),
    ("printer", "打印机"), ("scanner", "扫描仪"), ("speaker", "扬声器"),
    ("microphone", "麦克风"), ("webcam", "摄像头"),
    ("hardware", "硬件"), ("software", "软件"),
    ("operating system", "操作系统"), ("Windows", "Windows系统"),
    ("macOS", "苹果系统"), ("Linux", "Linux系统"),
    ("program", "程序"), ("application", "应用程序"),
    ("app", "应用"), ("browser", "浏览器"), ("search engine", "搜索引擎"),
    ("website", "网站"), ("webpage", "网页"), ("link", "链接"),
    ("URL", "网址"), ("download", "下载"), ("upload", "上传"),
    ("install", "安装"), ("uninstall", "卸载"), ("update", "更新"),
    ("upgrade", "升级"), ("backup", "备份"), ("restore", "恢复"),
    ("file", "文件"), ("folder", "文件夹"), ("document", "文档"),
    ("image", "图片"), ("video", "视频"), ("audio", "音频"),
    ("database", "数据库"), ("server", "服务器"), ("network", "网络"),
    ("cloud", "云"), ("storage", "存储"), ("memory", "内存"),
    ("hard drive", "硬盘"), ("SSD", "固态硬盘"), ("USB", "U盘"),
    ("Internet", "互联网"), ("WiFi", "无线网络"), ("ethernet", "以太网"),
    ("IP address", "IP地址"), ("domain", "域名"), ("protocol", "协议"),
    ("email", "电子邮件"), ("password", "密码"), ("username", "用户名"),
    ("login", "登录"), ("logout", "退出"), ("sign up", "注册"),
    ("encryption", "加密"), ("firewall", "防火墙"), ("antivirus", "杀毒软件"),
    ("virus", "病毒"), ("malware", "恶意软件"), ("hacker", "黑客"),
    ("data", "数据"), ("algorithm", "算法"), ("programming", "编程"),
    ("coding", "编码"), ("debug", "调试"), ("compile", "编译"),
    ("code", "代码"), ("script", "脚本"), ("function", "函数"),
    ("variable", "变量"), ("loop", "循环"), ("condition", "条件"),
    ("array", "数组"), ("object", "对象"), ("class", "类"),
    ("API", "应用程序接口"), ("framework", "框架"), ("library", "库"),
    ("artificial intelligence", "人工智能"), ("machine learning", "机器学习"),
    ("deep learning", "深度学习"), ("neural network", "神经网络"),
    ("data science", "数据科学"), ("big data", "大数据"),
    ("blockchain", "区块链"), ("cryptocurrency", "加密货币"),
    ("Bitcoin", "比特币"), ("NFT", "非同质化代币"),
    ("virtual reality", "虚拟现实"), ("augmented reality", "增强现实"),
    ("robot", "机器人"), ("automation", "自动化"),
    ("chatbot", "聊天机器人"), ("IoT", "物联网"),
    ("3D printing", "3D打印"), ("quantum computing", "量子计算"),
    ("cybersecurity", "网络安全"), ("privacy", "隐私"),
    ("social media", "社交媒体"), ("Facebook", "脸书"),
    ("Twitter", "推特"), ("Instagram", "Instagram"),
    ("YouTube", "YouTube"), ("TikTok", "抖音"),
    ("influencer", "网红"), ("viral", "病毒式传播"),
    ("digital", "数字的"), ("analog", "模拟的"),
    ("bit", "比特"), ("byte", "字节"), ("gigabyte", "吉字节"),
    ("megabyte", "兆字节"), ("terabyte", "太字节"),
    ("frequency", "频率"), ("bandwidth", "带宽"), ("latency", "延迟"),
    ("Bluetooth", "蓝牙"), ("NFC", "近场通信"), ("GPS", "全球定位系统"),
    ("interface", "界面"), ("user experience", "用户体验"),
    ("user interface", "用户界面"), ("responsive", "响应式的"),
    ("open source", "开源"), ("closed source", "闭源"),
    ("version control", "版本控制"), ("Git", "Git"),
    ("repository", "仓库"), ("branch", "分支"), ("commit", "提交"),
    ("push", "推送"), ("pull", "拉取"), ("merge", "合并"),
]

# 15. LAW & LEGAL (~3000 words)
law_legal = [
    # Criminal Law (~300)
    ("crime", "犯罪"), ("criminal", "罪犯"), ("felony", "重罪"), ("misdemeanor", "轻罪"),
    ("murder", "谋杀"), ("manslaughter", "过失杀人"), ("homicide", "杀人"),
    ("assault", "攻击"), ("battery", "殴打"), ("robbery", "抢劫"),
    ("burglary", "入室盗窃"), ("theft", "盗窃"), ("larceny", "盗窃罪"),
    ("fraud", "欺诈"), ("forgery", "伪造"), ("embezzlement", "挪用公款"),
    ("bribery", "贿赂"), ("extortion", "敲诈"), ("blackmail", "勒索"),
    ("kidnapping", "绑架"), ("arson", "纵火"), ("vandalism", "故意破坏"),
    ("trespassing", "非法入侵"), ("drug trafficking", "贩毒"),
    ("possession", "持有"), ("distribution", "分销"),
    ("perjury", "伪证"), ("obstruction of justice", "妨碍司法"),
    ("contempt of court", "藐视法庭"), ("money laundering", "洗钱"),
    ("identity theft", "身份盗窃"), ("cybercrime", "网络犯罪"),
    ("hate crime", "仇恨犯罪"), ("white-collar crime", "白领犯罪"),
    ("domestic violence", "家庭暴力"), ("child abuse", "虐待儿童"),
    ("sexual assault", "性侵犯"), ("rape", "强奸"),
    ("harassment", "骚扰"), ("stalking", "跟踪"),
    ("smuggling", "走私"), ("trafficking", "贩卖"),
    ("conspiracy", "共谋"), ("attempt", "未遂"),
    ("accessory", "从犯"), ("accomplice", "共犯"),
    ("principal", "主犯"), ("intent", "故意"), ("motive", "动机"),
    ("premeditation", "预谋"), ("self-defense", "自卫"),
    ("defense", "辩护"), ("alibi", "不在场证明"),
    ("evidence", "证据"), ("proof", "证明"), ("testimony", "证词"),
    ("witness", "证人"), ("victim", "受害者"), ("suspect", "嫌疑人"),
    ("defendant", "被告"), ("plaintiff", "原告"), ("prosecutor", "检察官"),
    ("defense attorney", "辩护律师"), ("judge", "法官"), ("jury", "陪审团"),
    ("verdict", " verdict"), ("guilty", "有罪"), ("innocent", "无罪"),
    ("acquittal", "无罪释放"), ("conviction", "定罪"),
    ("sentence", "判决"), ("punishment", "惩罚"), ("fine", "罚款"),
    ("probation", "缓刑"), ("parole", "假释"), ("imprisonment", "监禁"),
    ("life imprisonment", "终身监禁"), ("death penalty", "死刑"),
    ("appeal", "上诉"), ("overturn", "推翻判决"),
    ("bail", "保释"), ("indictment", "起诉书"), ("arraignment", "传讯"),
    ("plea", "认罪答辩"), ("plea bargain", "认罪协议"),
    ("Miranda rights", "米兰达权利"), ("search warrant", "搜查令"),
    ("arrest warrant", "逮捕令"), ("subpoena", "传票"),
    ("detention", "拘留"), ("custody", "羁押"), ("interrogation", "审讯"),
    ("Miranda warning", "米兰达警告"), ("right to remain silent", "保持沉默的权利"),
    ("right to attorney", "聘请律师的权利"),
    ("due process", "正当程序"), ("equal protection", "平等保护"),
    ("cruel and unusual punishment", "残忍和非常的惩罚"),
    ("double jeopardy", "双重危险"), ("statute of limitations", "诉讼时效"),
    ("habeas corpus", "人身保护令"), ("ex post facto", "事后法"),
    ("bill of rights", "权利法案"), ("constitutional rights", "宪法权利"),

    # Civil Law (~400)
    ("civil law", "民法"), ("contract", "合同"), ("tort", "侵权"),
    ("negligence", "过失"), ("breach of contract", "违约"),
    ("damages", "损害赔偿"), ("compensation", "赔偿"),
    ("injunction", "禁令"), ("specific performance", "实际履行"),
    ("rescission", "解除合同"), ("restitution", "归还"),
    ("liability", "责任"), ("strict liability", "严格责任"),
    ("product liability", "产品责任"),
    ("defamation", "诽谤"), ("slander", "口头诽谤"), ("libel", "书面诽谤"),
    ("invasion of privacy", "侵犯隐私"),
    ("intellectual property", "知识产权"), ("copyright", "版权"),
    ("trademark", "商标"), ("patent", "专利"), ("trade secret", "商业秘密"),
    ("plagiarism", "剽窃"), ("infringement", "侵权"),
    ("licensing", "许可"), ("royalty", "版税"),
    ("property law", "财产法"), ("real estate", "房地产"),
    ("title", "所有权"), ("deed", "契据"), ("mortgage", "抵押"),
    ("easement", "地役权"), ("zoning", "分区"),
    ("lease", "租赁"), ("landlord", "房东"), ("tenant", "租客"),
    ("eviction", "驱逐"), ("foreclosure", "止赎"),
    ("inheritance", "继承"), ("will", "遗嘱"), ("trust", "信托"),
    ("estate", "遗产"), ("probate", "遗嘱认证"),
    ("intestate", "无遗嘱"), ("heir", "继承人"), ("beneficiary", "受益人"),
    ("family law", "家庭法"), ("marriage", "婚姻"), ("divorce", "离婚"),
    ("child custody", "子女监护权"), ("visitation", "探视权"),
    ("child support", "子女抚养费"), ("alimony", "赡养费"),
    ("prenuptial agreement", "婚前协议"), ("adoption", "收养"),
    ("paternity", "亲子关系"), ("guardianship", "监护权"),
    ("domestic partnership", "同居关系"),
    ("employment law", "劳动法"), ("wrongful termination", "不当解雇"),
    ("discrimination", "歧视"), ("harassment", "骚扰"),
    ("wage and hour", "工资工时"), ("minimum wage", "最低工资"),
    ("overtime", "加班"), ("workers compensation", "工伤保险"),
    ("unemployment benefits", "失业救济"), ("labor union", "工会"),
    ("collective bargaining", "集体谈判"), ("strike", "罢工"),
    ("non-compete agreement", "竞业禁止协议"),
    ("non-disclosure agreement", "保密协议"),
    ("severance", "遣散费"), ("employment contract", "雇佣合同"),
    ("independent contractor", "独立承包人"),
    ("consumer law", "消费者法"), ("warranty", "保修"),
    ("lemon law", "柠檬法"), ("product recall", "产品召回"),
    ("false advertising", "虚假广告"), ("consumer protection", "消费者保护"),
    ("insurance law", "保险法"), ("policy", "保单"),
    ("claim", "索赔"), ("coverage", "承保范围"),
    ("deductible", "免赔额"), ("premium", "保费"),
    ("bad faith", "恶意"), ("underwriting", "承保"),

    # Constitutional & Administrative Law (~200)
    ("constitution", "宪法"), ("amendment", "修正案"),
    ("constitutional law", "宪法学"), ("separation of powers", "三权分立"),
    ("checks and balances", "制衡"), ("federalism", "联邦制"),
    ("states rights", "州权"), ("supremacy clause", "最高条款"),
    ("commerce clause", "商业条款"), ("due process clause", "正当程序条款"),
    ("equal protection clause", "平等保护条款"),
    ("freedom of speech", "言论自由"), ("freedom of religion", "宗教自由"),
    ("freedom of press", "新闻自由"), ("freedom of assembly", "集会自由"),
    ("right to bear arms", "持枪权"), ("right to vote", "投票权"),
    ("search and seizure", "搜查和扣押"), ("probable cause", "合理根据"),
    ("exclusionary rule", "排除规则"), ("self-incrimination", "自证其罪"),
    ("double jeopardy", "双重危险"), ("speedy trial", "迅速审判"),
    ("public trial", "公开审判"), ("impartial jury", "公正陪审团"),
    ("cruel and unusual punishment", "残酷和异常惩罚"),
    ("administrative law", "行政法"), ("regulation", "规章"),
    ("agency", "行政机关"), ("rulemaking", "制定规则"),
    ("adjudication", "裁决"), ("judicial review", "司法审查"),
    ("freedom of information", "信息自由"), ("sunshine law", "阳光法"),
    ("delegation", "授权"), ("discretion", "自由裁量权"),
    ("abuse of discretion", "滥用自由裁量权"),
    ("arbitrary and capricious", "任意和反复无常的"),
    ("standing", "诉讼资格"), ("ripeness", "成熟性"),
    ("mootness", "诉讼无意义"),
    ("exhaustion of remedies", "用尽救济手段"),

    # International Law (~200)
    ("international law", "国际法"), ("treaty", "条约"),
    ("convention", "公约"), ("protocol", "议定书"),
    ("declaration", "宣言"), ("customary international law", "国际习惯法"),
    ("jus cogens", "强制法"), ("erga omnes", "对一切义务"),
    ("sovereignty", "主权"), ("jurisdiction", "管辖"),
    ("territory", "领土"), ("extraterritoriality", "域外效力"),
    ("diplomatic immunity", "外交豁免权"),
    ("state immunity", "国家豁免"),
    ("United Nations", "联合国"), ("Security Council", "安全理事会"),
    ("General Assembly", "联合国大会"), ("International Court of Justice", "国际法院"),
    ("International Criminal Court", "国际刑事法院"),
    ("World Trade Organization", "世界贸易组织"),
    ("human rights", "人权"), ("genocide", "种族灭绝"),
    ("war crimes", "战争罪"), ("crimes against humanity", "反人类罪"),
    ("torture", "酷刑"), ("asylum", "庇护"), ("refugee", "难民"),
    ("extradition", "引渡"), ("mutual legal assistance", "司法协助"),
    ("international arbitration", "国际仲裁"),
    ("investment treaty", "投资条约"), ("BIT", "双边投资协定"),
    ("most favored nation", "最惠国"), ("national treatment", "国民待遇"),
    ("sanctions", "制裁"), ("embargo", "禁运"),
    ("law of the sea", "海洋法"), ("UNCLOS", "联合国海洋法公约"),
    ("territorial waters", "领海"), ("exclusive economic zone", "专属经济区"),
    ("air law", "航空法"), ("space law", "太空法"),
    ("international humanitarian law", "国际人道法"),
    ("Geneva Convention", "日内瓦公约"), ("Hague Convention", "海牙公约"),
    ("rules of engagement", "交战规则"), ("combatant", "战斗人员"),
    ("civilian", "平民"), ("protected person", "受保护人员"),
    ("prisoner of war", "战俘"), ("red cross", "红十字"),

    # Corporate & Business Law (~300)
    ("corporate law", "公司法"), ("corporation", "公司"),
    ("limited liability company", "有限责任公司"), ("partnership", "合伙"),
    ("joint venture", "合资企业"), ("holding company", "控股公司"),
    ("subsidiary", "子公司"), ("parent company", "母公司"),
    ("board of directors", "董事会"), ("shareholder", "股东"),
    ("shareholder meeting", "股东大会"), ("proxy", "代理投票"),
    ("fiduciary duty", "信托义务"), ("duty of care", "谨慎义务"),
    ("duty of loyalty", "忠诚义务"), ("business judgment rule", "商业判断规则"),
    ("piercing the corporate veil", "刺破公司面纱"),
    ("merger", "合并"), ("acquisition", "收购"),
    ("tender offer", "要约收购"), ("hostile takeover", "敌意收购"),
    ("poison pill", "毒丸计划"), ("golden parachute", "黄金降落伞"),
    ("antitakeover", "反收购"), ("SEC", "美国证券交易委员会"),
    ("securities law", "证券法"), ("prospectus", "招股说明书"),
    ("insider trading", "内幕交易"), ("disclosure", "披露"),
    ("material information", "重大信息"), ("registration", "注册"),
    ("bankruptcy", "破产"), ("Chapter 7", "第七章破产"),
    ("Chapter 11", "第十一章破产"), ("Chapter 13", "第十三章破产"),
    ("creditor", "债权人"), ("debtor", "债务人"),
    ("liquidation", "清算"), ("reorganization", "重组"),
    ("automatic stay", "自动中止"), ("trustee", "受托人"),
    ("secured debt", "担保债务"), ("unsecured debt", "无担保债务"),
    ("priority", "优先权"), ("discharge", "债务免除"),
    ("antitrust law", "反垄断法"), ("monopoly", "垄断"),
    ("monopolization", "垄断化"), ("price fixing", "价格固定"),
    ("market allocation", "市场分配"), ("bid rigging", "投标操纵"),
    ("predatory pricing", "掠夺性定价"), ("tying", "捆绑销售"),
    ("exclusive dealing", "独家交易"), ("merger review", "合并审查"),
    ("relevant market", "相关市场"), ("market power", "市场力量"),
    ("HHI index", "赫芬达尔指数"),
    ("tax law", "税法"), ("income tax", "所得税"),
    ("corporate tax", "公司税"), ("capital gains tax", "资本利得税"),
    ("value added tax", "增值税"), ("sales tax", "销售税"),
    ("property tax", "财产税"), ("estate tax", "遗产税"),
    ("gift tax", "赠与税"), ("tax deduction", "税收扣除"),
    ("tax credit", "税收抵免"), ("tax avoidance", "避税"),
    ("tax evasion", "逃税"), ("tax shelter", "避税工具"),
    ("transfer pricing", "转让定价"), ("double taxation", "双重征税"),
    ("tax treaty", "税收协定"), ("tax return", "纳税申报表"),
    ("IRS", "美国国税局"), ("audit", "审计"), ("appeal", "上诉"),

    # Legal Procedure & Practice (~400)
    ("jurisdiction", "管辖权"), ("venue", "审判地"),
    ("subject matter jurisdiction", "事物管辖权"),
    ("personal jurisdiction", "属人管辖权"),
    ("diversity jurisdiction", "异籍管辖权"),
    ("federal question jurisdiction", "联邦问题管辖权"),
    ("removal", "移送管辖"), ("forum non conveniens", "不方便法院"),
    ("pleading", "诉辩状"), ("complaint", "起诉状"),
    ("answer", "答辩状"), ("counterclaim", "反诉"),
    ("cross-claim", "交叉诉讼"), ("third-party claim", "第三方诉讼"),
    ("motion", "动议"), ("motion to dismiss", "驳回动议"),
    ("motion for summary judgment", "即决判决动议"),
    ("motion in limine", "预先排除动议"),
    ("discovery", "证据开示"), ("interrogatories", "书面质询"),
    ("deposition", "证词录证"), ("request for production", "文件请求"),
    ("request for admission", "自认请求"),
    ("subpoena", "传票"), ("subpoena duces tecum", "提交文件传票"),
    ("privilege", "特权"), ("attorney-client privilege", "律师-客户特权"),
    ("work product doctrine", "工作成果原则"),
    ("confidentiality", "保密性"), ("protective order", "保护令"),
    ("pretrial", "审前"), ("trial", "审判"),
    ("opening statement", "开场陈述"), ("closing argument", "结案陈词"),
    ("direct examination", "直接询问"),
    ("cross-examination", "交叉询问"), ("redirect", "再次直接询问"),
    ("recross", "再次交叉询问"), ("objection", "反对"),
    ("sustained", "反对有效"), ("overruled", "反对无效"),
    ("hearsay", "传闻证据"), ("relevance", "相关性"),
    ("materiality", "实质性"), ("competence", "能力"),
    ("credibility", "可信度"), ("impeachment", "质疑证人"),
    ("leading question", "诱导性问题"), ("expert witness", "专家证人"),
    ("lay witness", "普通证人"), ("character evidence", "品格证据"),
    ("circumstantial evidence", "间接证据"),
    ("direct evidence", "直接证据"), ("documentary evidence", "书证"),
    ("physical evidence", "物证"), ("real evidence", "实物证据"),
    ("demonstrative evidence", "演示证据"),
    ("burden of proof", "举证责任"), ("preponderance of evidence", "优势证据"),
    ("clear and convincing", "明确且令人信服的"),
    ("beyond a reasonable doubt", "排除合理怀疑"),
    ("presumption", "推定"), ("inference", "推断"),
    ("judicial notice", "司法认知"), ("stipulation", "约定"),
    ("jury instructions", "陪审团指示"), ("deliberation", "审议"),
    ("verdict", "裁决"), ("directed verdict", "指示裁决"),
    ("judgment NOV", "不顾裁决的判决"),
    ("new trial", "重新审判"), ("appeal", "上诉"),
    ("appellant", "上诉人"), ("appellee", "被上诉人"),
    ("brief", "上诉状"), ("oral argument", "口头辩论"),
    ("standard of review", "审查标准"),
    ("de novo", "重新审查"), ("abuse of discretion", "滥用自由裁量权"),
    ("clearly erroneous", "明显错误"),
    ("substantial evidence", "实质性证据"),
    ("affirm", "维持原判"), ("reverse", "推翻"),
    ("remand", "发回重审"), ("vacate", "撤销"),
    ("en banc", "全席审理"), ("per curiam", "法院意见"),
    ("majority opinion", "多数意见"), ("concurring opinion", "同意意见"),
    ("dissenting opinion", "反对意见"), ("plurality opinion", "复数意见"),
    ("precedent", "先例"), ("stare decisis", "遵循先例"),
    ("binding precedent", "有约束力的先例"),
    ("persuasive authority", "有说服力的权威"),
    ("holding", "判决要点"), ("dicta", "附带意见"),
    ("case law", "判例法"), ("common law", "普通法"),
    ("statutory interpretation", "法律解释"),
    ("plain meaning rule", "平义规则"),
    ("legislative history", "立法历史"), ("canons of construction", "解释准则"),
    ("ejusdem generis", "同类原则"), ("expressio unius", "明示其一原则"),
    ("noscitur a sociis", "文义关联"),
    ("legal ethics", "法律道德"), ("conflict of interest", "利益冲突"),
    ("professional conduct", "职业行为"), ("malpractice", "渎职"),
    ("disbarment", "取消律师资格"), ("suspension", "暂停执业"),
    ("pro bono", "公益法律服务"), ("contingency fee", "风险代理费"),
    ("hourly fee", "按小时收费"), ("retainer", "聘用费"),
    ("legal aid", "法律援助"), ("public defender", "公设辩护人"),

    # Chinese Law Specific (~200)
    ("Chinese legal system", "中国法律体系"),
    ("socialist rule of law", "社会主义法治"),
    ("National People's Congress", "全国人民代表大会"),
    ("Standing Committee", "常务委员会"),
    ("Supreme People's Court", "最高人民法院"),
    ("Supreme People's Procuratorate", "最高人民检察院"),
    ("People's Court", "人民法院"), ("People's Procuratorate", "人民检察院"),
    ("court levels", "法院级别"),
    ("basic court", "基层人民法院"),
    ("intermediate court", "中级人民法院"),
    ("high court", "高级人民法院"),
    ("civil procedure law", "民事诉讼法"),
    ("criminal procedure law", "刑事诉讼法"),
    ("administrative procedure law", "行政诉讼法"),
    ("contract law", "合同法"), ("tort liability law", "侵权责任法"),
    ("property law", "物权法"), ("marriage law", "婚姻法"),
    ("labor law", "劳动法"), ("company law", "公司法"),
    ("securities law", "证券法"), ("bankruptcy law", "企业破产法"),
    ("anti-monopoly law", "反垄断法"),
    ("foreign investment law", "外商投资法"),
    ("e-commerce law", "电子商务法"),
    ("cybersecurity law", "网络安全法"),
    ("data security law", "数据安全法"),
    ("personal information protection law", "个人信息保护法"),
    ("copyright law", "著作权法"), ("patent law", "专利法"),
    ("trademark law", "商标法"), ("anti-unfair competition law", "反不正当竞争法"),
    ("consumer protection law", "消费者权益保护法"),
    ("product quality law", "产品质量法"),
    ("food safety law", "食品安全法"),
    ("environmental protection law", "环境保护法"),
    ("administrative license law", "行政许可法"),
    ("administrative punishment law", "行政处罚法"),
    ("administrative reconsideration law", "行政复议法"),
    ("legislation law", "立法法"),
    ("criminal law of China", "中华人民共和国刑法"),
    ("death penalty with reprieve", "死刑缓期执行"),
    ("public security organ", "公安机关"),
    ("state security organ", "国家安全机关"),
    ("judicial organ", "司法机关"),
    ("procuratorial organ", "检察机关"),
    ("legal supervision", "法律监督"),
    ("arrest approval", "逮捕批准"),
    ("prosecution", "公诉"), ("private prosecution", "自诉"),
    ("criminal detention", "刑事拘留"),
    ("residential surveillance", "监视居住"),
    ("bail pending trial", "取保候审"),
    ("verdict of guilt", "有罪判决"),
    ("verdict of innocence", "无罪判决"),
    ("mediation", "调解"), ("arbitration", "仲裁"),
    ("notarization", "公证"), ("legal consultation", "法律咨询"),
    ("legal representative", "法定代表人"),
    ("power of attorney", "授权委托书"),
    ("statute of limitations in China", "中国诉讼时效"),
    ("choice of law", "法律选择"),
    ("foreign-related civil relations", "涉外民事关系"),
    ("recognition of foreign judgments", "外国判决的承认"),
    ("mutual legal assistance", "司法协助"),
]

# 16. SPORTS & EXERCISE (~300)
sports_exercise = [
    ("sports", "运动"), ("exercise", "锻炼"), ("game", "比赛"), ("match", "比赛"),
    ("team", "队伍"), ("player", "运动员"), ("coach", "教练"), ("referee", "裁判"),
    ("competition", "竞赛"), ("championship", "锦标赛"),
    ("Olympics", "奥运会"), ("World Cup", "世界杯"),
    ("football", "足球"), ("soccer", "英式足球"), ("basketball", "篮球"),
    ("volleyball", "排球"), ("tennis", "网球"), ("badminton", "羽毛球"),
    ("table tennis", "乒乓球"), ("baseball", "棒球"), ("golf", "高尔夫"),
    ("swimming", "游泳"), ("running", "跑步"), ("jogging", "慢跑"),
    ("cycling", "骑自行车"), ("hiking", "徒步"), ("climbing", "攀岩"),
    ("skiing", "滑雪"), ("skating", "滑冰"), ("surfing", "冲浪"),
    ("diving", "潜水"), ("boxing", "拳击"), ("wrestling", "摔跤"),
    ("martial arts", "武术"), ("karate", "空手道"), ("judo", "柔道"),
    ("taekwondo", "跆拳道"), ("kung fu", "功夫"),
    ("yoga", "瑜伽"), ("pilates", "普拉提"), ("dancing", "舞蹈"),
    ("gym", "健身房"), ("weightlifting", "举重"),
    ("aerobics", "有氧运动"), ("stretching", "拉伸"),
    ("training", "训练"), ("warm-up", "热身"), ("cool-down", "放松"),
    ("stamina", "耐力"), ("strength", "力量"), ("flexibility", "柔韧性"),
    ("speed", "速度"), ("agility", "敏捷性"), ("balance", "平衡"),
    ("score", "得分"), ("goal", "进球"), ("point", "分数"),
    ("win", "赢"), ("lose", "输"), ("draw", "平局"),
    ("gold medal", "金牌"), ("silver medal", "银牌"), ("bronze medal", "铜牌"),
    ("record", "纪录"), ("trophy", "奖杯"), ("medal", "奖牌"),
    ("stadium", "体育场"), ("gymnasium", "体育馆"), ("court", "球场"),
    ("field", "场地"), ("track", "跑道"), ("pool", "游泳池"),
    ("racket", "球拍"), ("ball", "球"), ("net", "网"),
    ("gloves", "手套"), ("helmet", "头盔"), ("protective gear", "护具"),
    ("uniform", "队服"), ("shorts", "短裤"), ("sneakers", "运动鞋"),
    ("marathon", "马拉松"), ("sprint", "短跑"), ("relay", "接力"),
    ("high jump", "跳高"), ("long jump", "跳远"), ("shot put", "铅球"),
    ("fencing", "击剑"), ("archery", "射箭"), ("shooting", "射击"),
    ("rowing", "划船"), ("sailing", "帆船"), ("canoeing", "皮划艇"),
    ("equestrian", "马术"), ("triathlon", "铁人三项"),
    ("weightlifting", "举重"), ("gymnastics", "体操"),
    ("figure skating", "花样滑冰"), ("speed skating", "速度滑冰"),
    ("ice hockey", "冰球"), ("curling", "冰壶"),
    ("cricket", "板球"), ("rugby", "橄榄球"), ("handball", "手球"),
    ("hockey", "曲棍球"), ("lacrosse", "长曲棍球"),
    ("snooker", "斯诺克"), ("billiards", "台球"), ("bowling", "保龄球"),
    ("darts", "飞镖"), ("chess", "国际象棋"), ("go", "围棋"),
    ("squash", "壁球"), ("racquetball", "壁球"), ("pickleball", "匹克球"),
    ("windsurfing", "风帆冲浪"), ("kitesurfing", "风筝冲浪"),
    ("skateboarding", "滑板"), ("rollerblading", "轮滑"),
    ("parkour", "跑酷"), ("zumba", "尊巴"),
    ("spectator", "观众"), ("fan", "粉丝"), ("cheerleader", "啦啦队"),
    ("anthem", "国歌"), ("opening ceremony", "开幕式"),
    ("closing ceremony", "闭幕式"), ("victory", "胜利"),
    ("defeat", " defeat"), ("comeback", "逆转"),
    ("underdog", "冷门"), ("upset", "爆冷"),
]

# 17. ENTERTAINMENT & CULTURE (~500)
entertainment = [
    ("movie", "电影"), ("film", "电影"), ("cinema", "电影院"),
    ("actor", "演员"), ("actress", "女演员"), ("director", "导演"),
    ("producer", "制片人"), ("screenplay", "剧本"),
    ("genre", "类型"), ("comedy", "喜剧"), ("drama", "剧情片"),
    ("horror", "恐怖片"), ("thriller", "惊悚片"), ("action", "动作片"),
    ("romance", "爱情片"), ("sci-fi", "科幻片"), ("documentary", "纪录片"),
    ("animation", "动画片"), ("musical", "音乐剧"),
    ("series", "连续剧"), ("episode", "剧集"), ("season", "季"),
    ("music", "音乐"), ("song", "歌曲"), ("singer", "歌手"),
    ("band", "乐队"), ("concert", "演唱会"), ("festival", "音乐节"),
    ("instrument", "乐器"), ("guitar", "吉他"), ("piano", "钢琴"),
    ("violin", "小提琴"), ("drums", "鼓"), ("flute", "笛子"),
    ("trumpet", "小号"), ("saxophone", "萨克斯"),
    ("orchestra", "管弦乐队"), ("symphony", "交响乐"),
    ("rock", "摇滚"), ("pop", "流行"), ("jazz", "爵士"),
    ("classical", "古典"), ("hip hop", "嘻哈"), ("R&B", "节奏蓝调"),
    ("folk", "民谣"), ("electronic", "电子音乐"),
    ("dance", "舞蹈"), ("ballet", "芭蕾"), ("modern dance", "现代舞"),
    ("art", "艺术"), ("painting", "绘画"), ("sculpture", "雕塑"),
    ("photography", "摄影"), ("exhibition", "展览"),
    ("museum", "博物馆"), ("gallery", "画廊"),
    ("literature", "文学"), ("poetry", "诗歌"), ("novel", "小说"),
    ("author", "作者"), ("writer", "作家"), ("poem", "诗"),
    ("play", "戏剧"), ("theater", "剧院"), ("performance", "表演"),
    ("ticket", "票"), ("audience", "观众"), ("stage", "舞台"),
    ("costume", "服装"), ("makeup", "化妆"), ("props", "道具"),
    ("game", "游戏"), ("video game", "电子游戏"),
    ("board game", "桌游"), ("card game", "纸牌游戏"),
    ("puzzle", "拼图"), ("crossword", "填字游戏"),
    ("reading", "阅读"), ("book", "书"), ("magazine", "杂志"),
    ("newspaper", "报纸"), ("comic", "漫画"),
    ("hobby", "爱好"), ("collection", "收藏"),
    ("travel", "旅行"), ("sightseeing", "观光"),
    ("photography", "摄影"), ("gardening", "园艺"),
    ("cooking", "烹饪"), ("baking", "烘焙"),
    ("fishing", "钓鱼"), ("camping", "露营"),
    ("karaoke", "卡拉OK"), ("singing", "唱歌"),
    ("internet", "上网"), ("social media", "社交媒体"),
    ("streaming", "流媒体"), ("podcast", "播客"),
    ("blog", "博客"), ("vlog", "视频博客"),
    ("painting", "画画"), ("drawing", "素描"),
    ("knitting", "编织"), ("sewing", "缝纫"),
    ("photography", "摄影"), ("calligraphy", "书法"),
    ("pottery", "陶艺"), ("woodworking", "木工"),
    ("astrology", "占星术"), ("tarot", "塔罗牌"),
    ("meditation", "冥想"), ("mindfulness", "正念"),
    ("volunteering", "志愿服务"), ("charity", "慈善"),
    ("philanthropy", "慈善事业"), ("donation", "捐赠"),
    ("festival", "节日"), ("celebration", "庆祝"),
    ("parade", "游行"), ("fireworks", "烟花"),
    ("tradition", "传统"), ("custom", "风俗"),
    ("religion", "宗教"), ("Buddhism", "佛教"),
    ("Christianity", "基督教"), ("Islam", "伊斯兰教"),
    ("Taoism", "道教"), ("Hinduism", "印度教"),
    ("church", "教堂"), ("temple", "寺庙"), ("mosque", "清真寺"),
    ("holiday", "节日"), ("vacation", "假期"),
    ("New Year", "新年"), ("Spring Festival", "春节"),
    ("Christmas", "圣诞节"), ("Easter", "复活节"),
    ("Thanksgiving", "感恩节"), ("Halloween", "万圣节"),
    ("Valentine's Day", "情人节"), ("Mother's Day", "母亲节"),
    ("Father's Day", "父亲节"), ("Children's Day", "儿童节"),
    ("National Day", "国庆节"), ("Mid-Autumn Festival", "中秋节"),
    ("Dragon Boat Festival", "端午节"), ("Lantern Festival", "元宵节"),
]

# === SENTENCES FROM VOCABULARY (~2000) ===
# Generate sentences using common patterns
sentence_patterns = [
    ("I like {}.", "我喜欢{}。"),
    ("I want {}.", "我想要{}。"),
    ("I have {}.", "我有{}。"),
    ("This is {}.", "这是{}。"),
    ("That is {}.", "那是{}。"),
    ("Where is {}?", "{}在哪里？"),
    ("I need {}.", "我需要{}。"),
    ("Can I get {}?", "我能得到{}吗？"),
    ("Do you have {}?", "你有{}吗？"),
    ("I love {}.", "我爱{}。"),
]
sentence_words_easy = [
    ("water", "水"), ("bread", "面包"), ("rice", "米饭"), ("milk", "牛奶"),
    ("tea", "茶"), ("coffee", "咖啡"), ("a pen", "一支笔"), ("a book", "一本书"),
    ("a chair", "一把椅子"), ("a table", "一张桌子"), ("a phone", "一部手机"),
    ("a computer", "一台电脑"), ("an apple", "一个苹果"), ("a banana", "一根香蕉"),
    ("an egg", "一个鸡蛋"), ("some bread", "一些面包"), ("some rice", "一些米饭"),
    ("cold water", "冷水"), ("hot tea", "热茶"), ("sweet coffee", "甜咖啡"),
]
sentences = []
for pattern_en, pattern_cn in sentence_patterns:
    for w, m in sentence_words_easy:
        sentences.append((pattern_en.format(w), pattern_cn.format(m)))
    if len(sentences) >= 500:
        break
# Add more sentence patterns
more_sentence_pairs = [
    ("How much is this?", "这个多少钱？"), ("Where is the bathroom?", "洗手间在哪里？"),
    ("What time is it?", "几点了？"), ("Can you help me?", "你能帮帮我吗？"),
    ("I don't understand.", "我不明白。"), ("Please speak slowly.", "请说慢点。"),
    ("I am learning English.", "我在学英语。"), ("What is your phone number?", "你的电话号码是多少？"),
    ("Nice to meet you.", "很高兴认识你。"), ("Where do you live?", "你住在哪里？"),
    ("I live in Beijing.", "我住在北京。"), ("How is the weather today?", "今天天气怎么样？"),
    ("It is sunny today.", "今天是晴天。"), ("Let's go for a walk.", "我们去散步吧。"),
    ("I am very happy.", "我很开心。"), ("That is a good idea.", "那是个好主意。"),
    ("What would you like to eat?", "你想吃什么？"), ("I would like some noodles.", "我想要一些面条。"),
    ("The food is delicious.", "这食物很好吃。"), ("Can I have the bill?", "我能买单吗？"),
    ("Excuse me, where is the station?", "打扰一下，车站在哪里？"),
    ("Turn left at the corner.", "在拐角处左转。"), ("Go straight ahead.", "一直往前走。"),
    ("How far is the airport?", "机场有多远？"), ("I need to buy a ticket.", "我需要买一张票。"),
    ("What time does the train leave?", "火车什么时候出发？"),
    ("I have a reservation.", "我有一个预约。"), ("Can I check in now?", "我现在可以办理入住吗？"),
    ("What is your name?", "你叫什么名字？"), ("My name is Li Ming.", "我的名字是李明。"),
    ("I am from China.", "我来自中国。"), ("I am a student.", "我是一个学生。"),
    ("I work in a company.", "我在一家公司工作。"), ("I get up at seven o'clock.", "我七点起床。"),
    ("I go to school by bus.", "我坐公交车去上学。"), ("I like reading books.", "我喜欢读书。"),
    ("She is a kind person.", "她是个善良的人。"), ("He is my best friend.", "他是我最好的朋友。"),
    ("We have a meeting today.", "我们今天有个会议。"), ("The meeting starts at 9 am.", "会议上午9点开始。"),
    ("I need to call my mother.", "我需要给我妈妈打电话。"), ("Please wait a moment.", "请稍等一下。"),
    ("I am sorry for the delay.", "很抱歉耽误了。"), ("Thank you for your help.", "谢谢你的帮助。"),
    ("You are welcome.", "不客气。"), ("Have a nice day.", "祝你愉快。"),
    ("See you tomorrow.", "明天见。"), ("Take care of yourself.", "照顾好自己。"),
    ("Good luck with your exam.", "祝你考试好运。"), ("Happy birthday to you!", "祝你生日快乐！"),
    ("I am very busy today.", "我今天很忙。"), ("I am tired after work.", "我下班后很累。"),
    ("Let's have dinner together.", "我们一起吃晚饭吧。"), ("What do you want to drink?", "你想喝什么？"),
    ("I will have a glass of water.", "我要一杯水。"), ("This restaurant is very good.", "这家餐厅很好。"),
    ("The service here is excellent.", "这里的服务非常好。"), ("I recommend this dish.", "我推荐这道菜。"),
    ("Could you take a photo for me?", "你能帮我拍张照片吗？"),
    ("What a beautiful view!", "多美的景色啊！"), ("I love this city.", "我爱这个城市。"),
    ("How long have you been here?", "你在这里多长时间了？"),
    ("I have been here for two years.", "我在这里两年了。"), ("Do you like Chinese food?", "你喜欢中国菜吗？"),
    ("I can speak a little Chinese.", "我会说一点点中文。"), ("That sounds great!", "听起来不错！"),
    ("I think it's a good idea.", "我认为这是个好主意。"), ("No problem.", "没问题。"),
    ("That makes sense.", "有道理。"), ("I agree with you.", "我同意你的看法。"),
    ("Let me think about it.", "让我想想。"), ("Please give me a call.", "请给我打电话。"),
    ("I will send you an email.", "我会给你发邮件。"), ("Can I have your number?", "我能要你的号码吗？"),
    ("Keep in touch!", "保持联系！"), ("I miss you very much.", "我很想你。"),
    ("I will be there soon.", "我很快就到。"), ("Wait for me.", "等等我。"),
    ("Don't worry.", "别担心。"), ("Everything will be fine.", "一切都会好起来的。"),
    ("I promise.", "我保证。"), ("I believe you.", "我相信你。"),
    ("Congratulations on your success!", "祝贺你的成功！"), ("I am proud of you.", "我为你骄傲。"),
    ("Well done!", "做得好！"), ("Keep up the good work!", "继续保持！"),
    ("You are doing great.", "你做得很好。"), ("Don't give up.", "不要放弃。"),
    ("Try your best.", "尽力而为。"), ("Practice makes perfect.", "熟能生巧。"),
    ("I'm sorry.", "对不起。"), ("It's not your fault.", "不是你的错。"),
    ("Please forgive me.", "请原谅我。"), ("Let's move on.", "我们继续吧。"),
    ("That's interesting.", "那很有趣。"), ("Tell me more.", "再跟我说说。"),
    ("I am curious about that.", "我对那个很好奇。"), ("What do you think?", "你怎么看？"),
    ("I can't believe it!", "我简直不敢相信！"), ("It's amazing!", "太神奇了！"),
    ("What a surprise!", "真惊喜！"), ("That's fantastic!", "太棒了！"),
]

# === CONVERSATION DIALOGUES (~500) ===
dialogues = [
    # Daily Conversations
    ("How was your day?", "你今天过得怎么样？"), ("It was great, thanks!", "很好，谢谢！"),
    ("What did you do today?", "你今天做了什么？"), ("I went shopping.", "我去购物了。"),
    ("Did you have fun?", "你玩得开心吗？"), ("Yes, I had a wonderful time.", "是的，我很开心。"),
    ("Are you free this weekend?", "你这周末有空吗？"), ("Yes, I'm free on Saturday.", "是的，我周六有空。"),
    ("Would you like to go out?", "你想出去吗？"), ("Sure, where would you like to go?", "当然，你想去哪里？"),
    ("Let's go to the cinema.", "我们去看电影吧。"), ("That sounds good.", "听起来不错。"),
    ("What movie do you want to see?", "你想看什么电影？"), ("I want to see a comedy.", "我想看喜剧片。"),
    ("What time does the movie start?", "电影几点开始？"), ("It starts at 7 pm.", "晚上7点开始。"),
    ("I will buy the tickets.", "我来买票。"), ("Thank you, that's very kind.", "谢谢，你太好了。"),
    ("What's your favorite food?", "你最喜欢的食物是什么？"), ("I love pizza!", "我喜欢披萨！"),
    ("Do you like cooking?", "你喜欢做饭吗？"), ("Yes, I enjoy cooking very much.", "是的，我很喜欢做饭。"),
    ("Can you teach me?", "你能教我吗？"), ("Of course, it's my pleasure.", "当然，我很乐意。"),
    ("How do you make this dish?", "这道菜怎么做？"), ("First, chop the vegetables.", "首先，切蔬菜。"),
    ("Then, stir-fry them.", "然后炒一下。"), ("Add some salt and pepper.", "加一些盐和胡椒粉。"),
    ("It looks delicious!", "看起来很好吃！"), ("Let me taste it.", "让我尝尝。"),
    ("Mmm, it's very good!", "嗯，很好吃！"), ("I'm glad you like it.", "很高兴你喜欢。"),
    ("Where do you work?", "你在哪里工作？"), ("I work at a technology company.", "我在一家科技公司工作。"),
    ("What is your job title?", "你的职位是什么？"), ("I am a software engineer.", "我是一名软件工程师。"),
    ("Do you like your job?", "你喜欢你的工作吗？"), ("Yes, I find it very interesting.", "是的，我觉得很有意思。"),
    ("How long have you worked there?", "你在那里工作多久了？"),
    ("I have worked there for three years.", "我在那里工作了三年。"),
    ("What do you do in your free time?", "你空闲时间做什么？"),
    ("I like to play basketball.", "我喜欢打篮球。"), ("Do you play any instruments?", "你会演奏乐器吗？"),
    ("I play the guitar.", "我会弹吉他。"), ("That's cool!", "真酷！"),
    ("Can you play a song for me?", "你能给我弹一首歌吗？"),
    ("Sure, I'll play my favorite song.", "当然，我弹我最喜欢的歌。"),

    # Professional Conversations
    ("We need to discuss the project.", "我们需要讨论这个项目。"),
    ("What is the deadline?", "截止日期是什么时候？"),
    ("The deadline is next Friday.", "截止日期是下周五。"),
    ("I will finish the report by Wednesday.", "我会在周三之前完成报告。"),
    ("Please send me the document.", "请把文件发给我。"),
    ("I will email it to you right away.", "我马上发邮件给你。"),
    ("Let's schedule a meeting for Monday.", "我们安排周一的会议。"),
    ("Does 10 am work for you?", "上午10点可以吗？"),
    ("That works for me.", "我没问题。"), ("I will send the meeting invitation.", "我会发送会议邀请。"),
    ("Please prepare the presentation.", "请准备演示文稿。"),
    ("What topics should I cover?", "我应该涵盖哪些主题？"),
    ("Focus on the key results.", "重点关注关键成果。"),
    ("I have some questions about the budget.", "我对预算有一些问题。"),
    ("Let me explain the details.", "我来解释一下细节。"),
    ("The budget has been approved.", "预算已经批准了。"),
    ("We need to reduce costs.", "我们需要降低成本。"),
    ("I suggest we review the expenses.", "我建议我们审查支出。"),
    ("That's a good suggestion.", "这是个好建议。"),
    ("Let's implement this plan.", "我们来实施这个计划。"),
    ("The client is very satisfied.", "客户非常满意。"),
    ("We need to follow up with them.", "我们需要跟进他们。"),
    ("I will contact them tomorrow.", "我明天会联系他们。"),
    ("Please keep me updated.", "请随时告诉我最新情况。"),
    ("Great work on the project!", "项目做得很好！"),

    # Travel Conversations
    ("I'd like to book a flight to London.", "我想订一张去伦敦的机票。"),
    ("When would you like to travel?", "你想什么时候出发？"),
    ("Next Monday, please.", "下周一，谢谢。"),
    ("One-way or round trip?", "单程还是往返？"),
    ("Round trip, please.", "往返，谢谢。"),
    ("How much does it cost?", "多少钱？"),
    ("The total is 500 dollars.", "总共500美元。"),
    ("Do you have any luggage?", "你有行李吗？"),
    ("I have one suitcase.", "我有一个行李箱。"),
    ("Here is your boarding pass.", "这是你的登机牌。"),
    ("What gate do I need to go to?", "我需要去哪个登机口？"),
    ("Gate 12, please proceed to boarding.", "12号登机口，请前往登机。"),
    ("Is the flight on time?", "航班准时吗？"),
    ("Yes, it's on schedule.", "是的，准时起飞。"),
    ("I'd like a window seat, please.", "我想要靠窗的位置。"),
    ("I prefer an aisle seat.", "我更喜欢过道的位置。"),
    ("Could I have a blanket, please?", "能给我一条毯子吗？"),
    ("What time do we arrive?", "我们什么时候到达？"),
    ("We will arrive at 3 pm local time.", "我们将在当地时间下午3点到达。"),
    ("Do you have anything to declare?", "你有什么要申报的吗？"),
    ("I have nothing to declare.", "我没有什么要申报的。"),
    ("Where can I collect my luggage?", "我在哪里取行李？"),
    ("Follow the signs to baggage claim.", "跟着指示牌去行李提取处。"),
    ("I need to exchange some currency.", "我需要换一些货币。"),
    ("Where is the currency exchange?", "货币兑换处在哪里？"),
    ("I'd like to exchange 200 dollars.", "我想换200美元。"),

    # Emergency Conversations
    ("Help! I need help!", "救命！我需要帮助！"),
    ("Call the police!", "报警！"), ("Call an ambulance!", "叫救护车！"),
    ("There is an emergency!", "有紧急情况！"),
    ("I need a doctor immediately.", "我需要马上看医生。"),
    ("I have lost my passport.", "我的护照丢了。"),
    ("Where is the police station?", "警察局在哪里？"),
    ("I need to report a theft.", "我需要报盗窃案。"),
    ("My wallet has been stolen.", "我的钱包被偷了。"),
    ("I am lost.", "我迷路了。"), ("Can you help me find this address?", "你能帮我找到这个地址吗？"),
    ("I don't feel well.", "我感觉不舒服。"), ("I have a fever.", "我发烧了。"),
    ("I am allergic to peanuts.", "我对花生过敏。"),
    ("I need a dentist.", "我需要看牙医。"), ("It hurts here.", "这里疼。"),
    ("Is there a hospital nearby?", "附近有医院吗？"),
    ("Please take me to the hospital.", "请带我去医院。"),
    ("I need medicine for a cold.", "我需要感冒药。"),
    ("How do I take this medicine?", "这药怎么吃？"),
    ("Take two pills three times a day.", "每天三次，每次两粒。"),
    ("I have health insurance.", "我有健康保险。"),
    ("Can I contact my embassy?", "我能联系我的大使馆吗？"),
    ("I need a new visa.", "我需要新的签证。"),
]

# Assemble all vocabulary
all_modules = [
    ("Basics", [
        ("greetings", greetings, "问候", 4),
        ("numbers", numbers_words + numbers_extras, "数字", 5),
        ("time-days", times, "时间和日期", 5),
        ("colors-shapes", colors, "颜色和形状", 4),
        ("family-people", family, "家庭和人际关系", 4),
        ("body-parts", body, "身体部位", 3),
    ]),
    ("Daily Life", [
        ("clothing", clothing, "服装和配饰", 4),
        ("daily-routines", daily_life[:250], "日常活动", 5),
        ("home-furniture", daily_life[250:], "家居和家具", 5),
        ("weather-nature", weather_nature[:150], "天气和自然", 4),
        ("animals-nature", weather_nature[150:], "动物和大自然", 4),
    ]),
    ("Food & Dining", [
        ("food-drinks", food[:250], "食物和饮料", 5),
        ("cooking-kitchen", food[250:], "烹饪和厨房", 4),
        ("restaurant", sentences[200:350], "餐厅用语", 4),
        ("flavors-tastes", sentences[150:250], "味道和口感", 3),
    ]),
    ("Travel", [
        ("transportation", more_sentence_pairs[:80], "交通工具", 4),
        ("directions-places", more_sentence_pairs[80:160], "方向和地点", 4),
        ("hotel-accommodation", more_sentence_pairs[160:220], "酒店住宿", 4),
        ("travel-dialogues", dialogues[100:160], "旅行对话", 4),
        ("international-travel", dialogues[160:200], "国际旅行", 4),
    ]),
    ("Shopping & Money", [
        ("shopping-basics", more_sentence_pairs[220:280], "购物基础", 4),
        ("clothes-shopping", more_sentence_pairs[280:340], "服装购物", 3),
        ("banking-money", more_sentence_pairs[340:390], "银行和货币", 3),
        ("shopping-dialogues", dialogues[:50], "购物对话", 4),
    ]),
    ("Health", [
        ("health-body", health[:200], "身体健康", 4),
        ("medicine-treatment", health[200:400], "医疗和药物", 4),
        ("mental-health", health[400:], "心理健康", 3),
        ("emergency", dialogues[200:245], "紧急情况", 4),
    ]),
    ("Education", [
        ("school-subjects", education[:200], "学校和科目", 5),
        ("academic-vocabulary", education[200:400], "学术词汇", 4),
        ("learning-skills", education[400:600], "学习技能", 4),
        ("exams-degrees", education[600:], "考试和学位", 4),
    ]),
    ("Work & Business", [
        ("professions", work_business[:150], "职业", 4),
        ("office-work", work_business[150:350], "办公室工作", 4),
        ("business-meetings", work_business[350:550], "商务会议", 4),
        ("finance-economy", work_business[550:750], "金融和经济", 4),
        ("career-hr", work_business[750:], "职业和人事", 4),
        ("business-conversations", dialogues[50:100], "商务对话", 4),
    ]),
    ("Law & Legal", [
        ("criminal-law", law_legal[:150], "刑法", 5),
        ("criminal-procedure", law_legal[150:300], "刑事诉讼", 4),
        ("civil-law-torts", law_legal[300:450], "民法和侵权", 4),
        ("property-family-law", law_legal[450:600], "财产法和家庭法", 4),
        ("corporate-law", law_legal[600:750], "公司法", 4),
        ("contract-tax-law", law_legal[750:900], "合同法和税法", 4),
        ("constitutional-law", law_legal[900:1000], "宪法", 4),
        ("international-law", law_legal[1000:1100], "国际法", 4),
        ("legal-procedure", law_legal[1100:1300], "法律程序", 5),
        ("legal-ethics", law_legal[1300:1400], "法律道德", 3),
        ("chinese-law-system", law_legal[1400:], "中国法律体系", 4),
    ]),
    ("Technology", [
        ("computers-hardware", technology[:120], "计算机硬件", 4),
        ("software-internet", technology[120:250], "软件和互联网", 4),
        ("programming", technology[250:380], "编程", 4),
        ("ai-data", technology[380:], "人工智能和数据", 4),
    ]),
    ("Sports & Exercise", [
        ("sports", sports_exercise[:150], "运动", 4),
        ("fitness-training", sports_exercise[150:], "健身和训练", 4),
    ]),
    ("Entertainment & Culture", [
        ("movies-tv", entertainment[:100], "电影和电视", 4),
        ("music-dance", entertainment[100:200], "音乐和舞蹈", 4),
        ("arts-literature", entertainment[200:300], "艺术和文学", 4),
        ("hobbies", entertainment[300:400], "爱好", 4),
        ("festivals-traditions", entertainment[400:], "节日和传统", 4),
        ("daily-conversations", more_sentence_pairs[390:], "日常对话", 4),
        ("conversation-dialogues", dialogues[245:], "会话对话", 4),
    ]),
    ("Sentences & Practice", [
        ("basic-sentences", sentences[:500], "基础句子", 5),
    ]),
]

# ============ GENERATE ALL FILES ============
print("=== Generating zh-en (English from Chinese) course ===")

module_defs = []
total_words = 0

for module_title, skills in all_modules:
    skill_defs = []
    for skill_href, words, skill_title, levels in skills:
        skill = write_skill(skill_href, words, skill_title, levels)
        skill_defs.append(skill)
        total_words += len(words)
    module_defs.append({"title": module_title, "skills": skill_defs})

course_data = {
    "languageName": "English",
    "languageCode": "en",
    "uiLanguage": "zh",
    "specialCharacters": ["'", "é", "á", "í", "ó", "ú", "ü"],
    "repositoryURL": "https://github.com/xixil136136-ui/LibreLingo",
    "license": {
        "name": {"short": "CC BY-SA 4.0", "full": "Attribution-ShareAlike 4.0 International"},
        "link": "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    },
    "modules": module_defs
}

course_data_path = "/Users/lys/LibreLingo/apps/librelingo-web/src/courses/zh-en/courseData.json"
with open(course_data_path, "w", encoding="utf-8") as f:
    json.dump(course_data, f, ensure_ascii=False, indent=2)
print(f"\ncourseData.json written to {course_data_path}")
print(f"\nTotal words generated: {total_words}")
print(f"Total challenge entries: {total_words * 2}")
print(f"Total skills: {sum(len(s) for _, s in all_modules)}")
print("=== Done! ===")
